"""Offline DDL dump of the engine's Postgres metadata schema.

Compiles the complete SQLAlchemy model metadata to PostgreSQL DDL without
connecting to any database. Output is deterministic — tables in FK topological
order, indexes sorted by name — so the result can be checked in and diffed.

The dump is schema-less (no ``CREATE SCHEMA`` / qualified names), matching how
the engine targets workspaces: a connection-level ``search_path`` decides which
``ws_<id>`` schema the tables land in.

Covers tables + indexes (constraints render inline). If models ever grow
native ENUMs or explicit Sequences, the CI drift gate fails loudly at psql
apply time — extend the loop then. Column ``comment=`` would be silently
dropped (create_all emits COMMENT ON separately); don't use it, or extend.

When given an output path, a sibling ``schema_read.sql`` is written next to it
— the promoted-read surface's view DDL (docs/architecture/persistence.md, ``storage/read_views.py``),
generated by the same mechanism and policed by the same CI drift gate.

Usage:
    uv run python -m dataraum.storage.dump_ddl [output_path]
"""

import sys
from pathlib import Path

from sqlalchemy.dialects.postgresql.base import PGDialect
from sqlalchemy.schema import CreateIndex, CreateTable

from dataraum.storage.base import Base, load_all_models

HEADER = """\
-- GENERATED by `uv run python -m dataraum.storage.dump_ddl` — do not edit.
-- Source of truth: the SQLAlchemy models (storage.base.load_all_models).
-- Schema-less on purpose: apply with search_path set to the target ws_<id>.
"""


def dump_ddl() -> str:
    """Compile all SQLAlchemy model tables to a PostgreSQL DDL script.

    Returns:
        The full engine metadata schema as one deterministic SQL script.
    """
    load_all_models()
    dialect = PGDialect()  # type: ignore[no-untyped-call]
    statements: list[str] = []
    for table in Base.metadata.sorted_tables:
        create_table = CreateTable(table).compile(dialect=dialect)
        statements.append(str(create_table).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name or ""):
            create_index = CreateIndex(index).compile(dialect=dialect)
            statements.append(str(create_index).strip() + ";")
    return HEADER + "\n" + "\n\n".join(statements) + "\n"


if __name__ == "__main__":
    from dataraum.storage.read_views import dump_read_ddl

    ddl = dump_ddl()
    if len(sys.argv) > 1:
        out = Path(sys.argv[1])
        out.write_text(ddl)
        out.with_name("schema_read.sql").write_text(dump_read_ddl())
    else:
        sys.stdout.write(ddl)
