/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List sources registered in the workspace
         * @description Return all non-archived sources in the workspace registry.
         *
         *     The shape mirrors the MCP ``list_sources`` tool's public fields. Empty
         *     list when no sources are registered.
         */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Substrate + DuckLake catalog + workspace Postgres health.
         *
         *     Returns 200 with ``status: ok`` when both substrate components are
         *     reachable; 503 with ``status: degraded`` otherwise so k8s/ECS readiness
         *     probes that only inspect the status code route traffic away from the
         *     container instead of seeing a healthy 200 with a degraded body.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Source
         * @description A data source registered in the workspace.
         *
         *     Mirrors the field set the MCP ``list_sources`` tool returned — same
         *     public shape, just an HTTP envelope. Sensitive fields (credentials,
         *     connection strings) are never surfaced.
         */
        Source: {
            /**
             * Name
             * @description Source name (unique within the workspace).
             */
            name: string;
            /**
             * Type
             * @description Source type discriminator: 'csv', 'parquet', 'json', 'jsonl', 'directory', 'db_recipe'.
             */
            type: string;
            /**
             * Status
             * @description Lifecycle status (e.g. 'configured').
             */
            status: string;
            /**
             * Path
             * @description Filesystem path for file/directory sources; recipe path for db_recipe sources.
             */
            path?: string | null;
            /**
             * Backend
             * @description Backend identifier for db_recipe sources (e.g. 'mssql'). Absent for file sources.
             */
            backend?: string | null;
            /**
             * Recipe Tables
             * @description Named SELECT queries declared in a db_recipe yaml. Absent for file sources.
             */
            recipe_tables?: string[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Source"][];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
