"""Document agent — LLM-powered domain knowledge elicitation.

Interacts with users to document domain knowledge for document_* actions.
Generates clarifying questions, interprets answers, and logs fixes.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, Field

from dataraum.core.logging import get_logger
from dataraum.core.models.base import Result
from dataraum.llm.prompts import PromptRenderer
from dataraum.llm.providers.base import (
    ConversationRequest,
    LLMProvider,
    Message,
    ToolDefinition,
)

logger = get_logger(__name__)


# --- Pydantic tool schemas ---


class ClarifyingQuestion(BaseModel):
    """A question to ask the user about their data."""

    question: str
    question_type: Literal["free_text", "multiple_choice"]
    choices: list[str] = Field(default_factory=list)


class DocumentFixQuestions(BaseModel):
    """Questions generated by the agent to elicit domain knowledge."""

    questions: list[ClarifyingQuestion]
    context_summary: str


class DocumentFixInterpretation(BaseModel):
    """Structured interpretation of user answers."""

    interpretation: str
    confidence: Literal["high", "medium", "low"]
    summary: str


# --- Agent ---


class DocumentAgent:
    """LLM-powered agent for eliciting domain knowledge from users.

    Uses the document_fix prompt template with two modes:
    - questions: Generate clarifying questions from action context
    - interpret: Interpret user answers into structured domain knowledge

    The agent receives comprehensive context (action details, entropy analysis,
    data profiles, related actions, existing fixes) in a single structured string.
    """

    def __init__(
        self,
        provider: LLMProvider,
        renderer: PromptRenderer,
        model: str,
    ) -> None:
        self.provider = provider
        self.renderer = renderer
        self.model = model

    def generate_questions(
        self,
        context: str,
    ) -> Result[DocumentFixQuestions]:
        """Generate clarifying questions for a document_* action.

        Args:
            context: Structured context string from _build_agent_context()

        Returns:
            Result containing DocumentFixQuestions
        """
        template_context = {
            "mode": "questions",
            "column_context": context,
            "user_answers": "",
        }

        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "document_fix", template_context
            )
        except Exception as e:
            return Result.fail(f"Failed to render prompt: {e}")

        tool = ToolDefinition(
            name="document_fix_questions",
            description="Generate questions to elicit domain knowledge from the user.",
            input_schema=DocumentFixQuestions.model_json_schema(),
        )

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "document_fix_questions"},
            max_tokens=2048,
            temperature=temperature,
            model=self.model,
        )

        response_result = self.provider.converse(request)
        if not response_result.success or not response_result.value:
            return Result.fail(response_result.error or "LLM call failed")

        response = response_result.value
        if not response.tool_calls:
            return Result.fail("LLM did not use the tool")

        try:
            output = DocumentFixQuestions.model_validate(response.tool_calls[0].input)
            return Result.ok(output)
        except Exception as e:
            return Result.fail(f"Failed to parse questions: {e}")

    def interpret_answers(
        self,
        context: str,
        user_answers: str,
    ) -> Result[DocumentFixInterpretation]:
        """Interpret user answers into structured domain knowledge.

        Args:
            context: Structured context string from _build_agent_context()
            user_answers: Formatted user answers to clarifying questions

        Returns:
            Result containing DocumentFixInterpretation
        """
        template_context = {
            "mode": "interpret",
            "column_context": context,
            "user_answers": user_answers,
        }

        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "document_fix", template_context
            )
        except Exception as e:
            return Result.fail(f"Failed to render prompt: {e}")

        tool = ToolDefinition(
            name="document_fix_interpretation",
            description="Provide structured interpretation of user answers.",
            input_schema=DocumentFixInterpretation.model_json_schema(),
        )

        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "document_fix_interpretation"},
            max_tokens=2048,
            temperature=temperature,
            model=self.model,
        )

        response_result = self.provider.converse(request)
        if not response_result.success or not response_result.value:
            return Result.fail(response_result.error or "LLM call failed")

        response = response_result.value
        if not response.tool_calls:
            return Result.fail("LLM did not use the tool")

        try:
            output = DocumentFixInterpretation.model_validate(response.tool_calls[0].input)
            return Result.ok(output)
        except Exception as e:
            return Result.fail(f"Failed to parse interpretation: {e}")
