// Engine metadata Drizzle client — read-only access to the active workspace's
// Postgres schema in the engine substrate (DAT-339 pivot, slice 1).
//
// The schema TS (./schema.ts + ./relations.ts) is generated by
// `bun run db:pull:metadata` and normalized into clean export names. Emitted
// SQL is fully qualified by the schema name baked into pgSchema(), so this
// client does NOT need to set search_path.
//
// Source of truth: the engine's SQLAlchemy models. Never push from here.

import { SQL } from "bun";
import { drizzle } from "drizzle-orm/bun-sql";

import { config } from "../../config";
import { relations } from "./relations";

const client = new SQL(config.metadataDatabaseUrl);

// drizzle 1.0 takes a single options object. `relations` already encodes
// every table reference (via defineRelations(schema, ...)), so we don't need
// to pass `schema` separately. Tables are still importable from ./schema for
// .select().from(...) calls.
export const metadataDb = drizzle({ client, relations });
