// Engine metadata Drizzle clients — the two per-workspace ROLES the engine
// bootstrap mints (DAT-816). The role resolves the schema: each role carries
// `ALTER ROLE … SET search_path`, so the generated mirror (./schema.ts) and
// the hand-declared write surface (./write-surface.ts) emit UNQUALIFIED names
// and the cockpit holds zero workspace literals.
//
//   metadataDb      — the reader role (ws_<id>_reader): search_path pinned to
//                     the promoted-read schema ws_<id>_read, SELECT only there
//                     (ADR-0008 enforcement — raw run-stamped tables and other
//                     workspaces are unreachable).
//   metadataWriteDb — the writer role (ws_<id>_writer): search_path pinned to
//                     the raw ws_<id> schema, exactly the control-table verbs.
//
// The two stay SEPARATE connections by design: the read schema's pass-through
// views share names with the raw tables, so one merged search_path would make
// every unqualified name ambiguous about which surface it hits.
//
// The schema TS (./schema.ts + ./relations.ts) is generated by
// `bun run db:pull:metadata`. Source of truth: the engine's SQLAlchemy models.
// Never push from here.

import { SQL } from "bun";
import { drizzle } from "drizzle-orm/bun-sql";

import { config } from "../../config";
import { relations } from "./relations";

const client = new SQL(config.metadataDatabaseUrl);

// drizzle 1.0 takes a single options object. `relations` already encodes
// every table reference (via defineRelations(schema, ...)), so we don't need
// to pass `schema` separately. Tables are still importable from ./schema for
// .select().from(...) calls.
export const metadataDb = drizzle({ client, relations });

const writeClient = new SQL(config.metadataWriterDatabaseUrl);

// No `relations`: the write surface is four hand-declared control tables
// (./write-surface.ts) addressed directly with .select()/.insert()/.update().
export const metadataWriteDb = drizzle({ client: writeClient });
