// Build-time pre-bundle of the orchestration workflow code (DAT-529).
//
// The Temporal worker runs workflow code in a vm sandbox from a bundle. In dev
// the worker can bundle from source on boot (webpack + swc present), but the
// PRODUCTION server is a Nitro bundle with no workflow source or bundler on
// disk. So we pre-bundle here — at build time, where the toolchain exists — into
// a string that gets compiled INTO the server bundle (worker.ts imports it). The
// runtime then loads `workflowBundle: { code }` directly: no webpack, no swc, no
// workflow source shipped to prod (the runner stays slim).
//
// Run before `vite build` (see package.json). Emits a gitignored module under
// src/worker/generated/ that vite bundles in.

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { bundleWorkflowCode } from "@temporalio/worker";

const here = dirname(new URL(import.meta.url).pathname);
const workflowsPath = resolve(here, "../src/worker/workflows");
const outFile = resolve(here, "../src/worker/generated/workflow-bundle.ts");

const { code } = await bundleWorkflowCode({ workflowsPath });

await mkdir(dirname(outFile), { recursive: true });
await writeFile(
	outFile,
	`// GENERATED by scripts/build-workflow-bundle.ts — do not edit, do not commit.\n` +
		`// The pre-bundled orchestration workflow code (DAT-529/DAT-609), loaded by the\n` +
		`// worker as \`workflowBundle: { code }\` so prod needs no runtime bundler.\n` +
		`export const workflowBundleCode = ${JSON.stringify(code)};\n`,
);

console.log(
	`[build-workflow-bundle] wrote ${outFile} (${(code.length / 1024) | 0} KiB)`,
);
