// The co-located orchestration worker singleton (DAT-529).
//
// Lifecycle: created once when the cockpit server process boots (the Nitro
// plugin in src/server/plugins) and polls for the life of the process — so a
// run advances with NO browser tab open (the pain-#2 / tab-independence fix).
// It connects OUT to Temporal (no HTTP surface) and polls the cockpit's own
// orchestration task queue, distinct from the engine's per-workspace queues.
//
// Runs under Bun (proven on 1.3.14 + SDK 1.17.2; experimental Bun support landed
// in SDK 1.15 — see the project-temporal-worker-on-bun-proven memory). The one
// caveat is a benign boot warning: `v8.promiseHooks.createHook is not available`
// → workflow stack-trace queries are disabled; our own signals/queries are fine.
//
// Pure of `config`: it takes explicit Temporal params so the runtime can be
// smoke-tested with no full cockpit env; the boot plugin reads `config` and
// passes them in.

import { fileURLToPath } from "node:url";
import { NativeConnection, Worker } from "@temporalio/worker";
import * as activities from "./activities";

/** Resolve the workflow code source for `Worker.create`: the build-time
 * pre-bundle when present (prod), else bundle-from-source on boot (dev). */
async function resolveWorkflowSource(): Promise<
	{ workflowBundle: { code: string } } | { workflowsPath: string }
> {
	try {
		// Generated by scripts/build-workflow-bundle.ts — present after `bun run
		// build` (prod), absent in dev + at typecheck/CI. The indirected specifier
		// keeps tsc from resolving (and failing on) the not-yet-generated module;
		// at runtime an absent bundle throws and we fall back to workflowsPath.
		const generated = "./generated/workflow-bundle.js";
		const { workflowBundleCode } = (await import(generated)) as {
			workflowBundleCode: string;
		};
		return { workflowBundle: { code: workflowBundleCode } };
	} catch {
		// ESM-native resolution (no CJS `require` shim) — matches build-workflow-bundle.ts.
		return {
			workflowsPath: fileURLToPath(
				new URL("./workflows/index.ts", import.meta.url),
			),
		};
	}
}

export interface OrchestrationWorkerOptions {
	/** Temporal frontend address, host:port (config.temporalHost). */
	address: string;
	/** Temporal namespace (config.temporalNamespace). */
	namespace: string;
	/** The cockpit orchestration task queue (config.cockpitOrchestrationTaskQueue). */
	taskQueue: string;
}

export interface RunningOrchestrationWorker {
	readonly worker: Worker;
	/** Stop polling and close the connection; clears the singleton so a later
	 * start re-creates it. */
	shutdown(): Promise<void>;
}

// HMR / double-import guard. In dev (`vite dev`) modules are re-evaluated on hot
// reload; without a process-wide pin each reload would spawn ANOTHER poller
// against the same queue. Cache the in-flight start PROMISE on globalThis so a
// re-import reuses the running worker (mirrors the temporal CLIENT singleton in
// temporal/progress.ts, lifted to globalThis for HMR).
const SINGLETON = Symbol.for("dataraum.orchestrationWorker");
type Holder = { [SINGLETON]?: Promise<RunningOrchestrationWorker> };

/**
 * Start the orchestration worker, or return the already-running one. Idempotent
 * across HMR re-evaluation and concurrent callers (the start promise is shared);
 * a failed start clears the cache so a later boot can retry.
 */
export function startOrchestrationWorker(
	opts: OrchestrationWorkerOptions,
): Promise<RunningOrchestrationWorker> {
	const holder = globalThis as Holder;
	const existing = holder[SINGLETON];
	if (existing) return existing;

	const starting = (async (): Promise<RunningOrchestrationWorker> => {
		const connection = await NativeConnection.connect({
			address: opts.address,
		});
		const worker = await Worker.create({
			connection,
			namespace: opts.namespace,
			taskQueue: opts.taskQueue,
			// Workflow code: prefer the build-time PRE-BUNDLE (prod — no bundler or
			// workflow source on disk in the Nitro server image), and fall back to
			// bundling from source on boot in dev (where the toolchain is present).
			// This is the standard Temporal dev-source/prod-bundle split, not an
			// architecture fallback.
			...(await resolveWorkflowSource()),
			activities,
		});

		// run() resolves only when the worker stops; let it poll in the background.
		// A crash clears the singleton so a future boot can re-create it.
		const runPromise = worker.run();
		runPromise.catch((err) => {
			console.error("[orchestration-worker] poll loop crashed:", err);
			holder[SINGLETON] = undefined;
		});

		console.log(
			`[orchestration-worker] RUNNING — queue=${opts.taskQueue} ns=${opts.namespace}`,
		);

		return {
			worker,
			async shutdown() {
				worker.shutdown();
				await runPromise.catch(() => {});
				await connection.close();
				holder[SINGLETON] = undefined;
			},
		};
	})().catch((err) => {
		holder[SINGLETON] = undefined;
		throw err;
	});

	holder[SINGLETON] = starting;
	return starting;
}
