-- GENERATED by `uv run python -m dataraum.storage.dump_ddl` — do not edit.
-- Promoted-read surface (ADR-0008): current_* head-joined views for
-- run-stamped tables + same-named pass-throughs for the rest, plus the
-- analyzed-representative entity views current_tables/current_columns
-- (DAT-655: typed layer behind a promoted generation head).
-- Tokenized: __WS__ = raw workspace schema, __READ__ = read schema.
-- Appliers substitute both (engine bootstrap; pull-metadata.sh via sed).

DROP VIEW IF EXISTS __READ__.current_claim_witnesses;
CREATE VIEW __READ__.current_claim_witnesses AS
SELECT r.*,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'generation' AND h.run_id = r.run_id
      AND h.target = 'table:' || r.table_id
  ) AS via_table_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'catalog' AND h.run_id = r.run_id
      AND h.target = 'catalog'
  ) AS via_catalog_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'operating_model' AND h.run_id = r.run_id
      AND h.target = 'catalog'
  ) AS via_operating_model_head
FROM __WS__.claim_witnesses r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.run_id = r.run_id
    AND ((h.stage = 'generation'
      AND h.target = 'table:' || r.table_id)
     OR (h.stage = 'catalog' AND h.target = 'catalog')
     OR (h.stage = 'operating_model' AND h.target = 'catalog'))
)
;

DROP VIEW IF EXISTS __READ__.current_column_concepts;
CREATE VIEW __READ__.current_column_concepts AS
SELECT r.* FROM __WS__.column_concepts r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_column_eligibility;
CREATE VIEW __READ__.current_column_eligibility AS
SELECT r.* FROM __WS__.column_eligibility r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'table:' || r.table_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.columns;
CREATE VIEW __READ__.columns AS
SELECT * FROM __WS__.columns;

DROP VIEW IF EXISTS __READ__.config_overlay;
CREATE VIEW __READ__.config_overlay AS
SELECT * FROM __WS__.config_overlay;

DROP VIEW IF EXISTS __READ__.current_derived_columns;
CREATE VIEW __READ__.current_derived_columns AS
SELECT r.* FROM __WS__.derived_columns r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_detected_business_cycles;
CREATE VIEW __READ__.current_detected_business_cycles AS
SELECT r.* FROM __WS__.detected_business_cycles r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'operating_model'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_dimension_hierarchies;
CREATE VIEW __READ__.current_dimension_hierarchies AS
SELECT r.* FROM __WS__.dimension_hierarchies r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_driver_rankings;
CREATE VIEW __READ__.current_driver_rankings AS
SELECT r.* FROM __WS__.driver_rankings r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_enriched_views;
CREATE VIEW __READ__.current_enriched_views AS
SELECT r.* FROM __WS__.enriched_views r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_entropy_objects;
CREATE VIEW __READ__.current_entropy_objects AS
SELECT r.*,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'generation' AND h.run_id = r.run_id
      AND h.target = 'table:' || r.table_id
  ) AS via_table_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'catalog' AND h.run_id = r.run_id
      AND h.target = 'catalog'
  ) AS via_catalog_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'operating_model' AND h.run_id = r.run_id
      AND h.target = 'catalog'
  ) AS via_operating_model_head
FROM __WS__.entropy_objects r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.run_id = r.run_id
    AND ((h.stage = 'generation'
      AND h.target = 'table:' || r.table_id)
     OR (h.stage = 'catalog' AND h.target = 'catalog')
     OR (h.stage = 'operating_model' AND h.target = 'catalog'))
)
;

DROP VIEW IF EXISTS __READ__.current_entropy_readiness;
CREATE VIEW __READ__.current_entropy_readiness AS
SELECT r.*,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'generation' AND h.run_id = r.run_id
      AND h.target = 'table:' || r.table_id
  ) AS via_table_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'catalog' AND h.run_id = r.run_id
      AND h.target = 'catalog'
  ) AS via_catalog_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'operating_model' AND h.run_id = r.run_id
      AND h.target = 'catalog'
  ) AS via_operating_model_head
FROM __WS__.entropy_readiness r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.run_id = r.run_id
    AND ((h.stage = 'generation'
      AND h.target = 'table:' || r.table_id)
     OR (h.stage = 'catalog' AND h.target = 'catalog')
     OR (h.stage = 'operating_model' AND h.target = 'catalog'))
)
  AND (
    NOT EXISTS (
      SELECT 1 FROM __WS__.metadata_snapshot_head h3
      WHERE h3.run_id = r.run_id
        AND h3.target = 'catalog'
        AND h3.stage IN ('catalog', 'operating_model')
    )
    OR NOT EXISTS (
      SELECT 1 FROM __WS__.entropy_readiness r2
      JOIN __WS__.metadata_snapshot_head h2
        ON h2.run_id = r2.run_id
       AND h2.target = 'catalog'
       AND h2.stage IN ('catalog', 'operating_model')
      WHERE r2.target = r.target
        AND r2.run_id <> r.run_id
        AND h2.promoted_at > (
          SELECT MAX(h3.promoted_at)
          FROM __WS__.metadata_snapshot_head h3
          WHERE h3.run_id = r.run_id
            AND h3.target = 'catalog'
            AND h3.stage IN ('catalog', 'operating_model')
        )
    )
  )
;

DROP VIEW IF EXISTS __READ__.current_lifecycle_artifacts;
CREATE VIEW __READ__.current_lifecycle_artifacts AS
SELECT r.* FROM __WS__.lifecycle_artifacts r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'operating_model'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_materialization_recipes;
CREATE VIEW __READ__.current_materialization_recipes AS
SELECT r.* FROM __WS__.materialization_recipes r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'table:' || r.table_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_measure_aggregation_lineage;
CREATE VIEW __READ__.current_measure_aggregation_lineage AS
SELECT r.* FROM __WS__.measure_aggregation_lineage r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.metadata_snapshot_head;
CREATE VIEW __READ__.metadata_snapshot_head AS
SELECT * FROM __WS__.metadata_snapshot_head;

DROP VIEW IF EXISTS __READ__.current_relationships;
CREATE VIEW __READ__.current_relationships AS
SELECT r.* FROM __WS__.relationships r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.run_tables;
CREATE VIEW __READ__.run_tables AS
SELECT * FROM __WS__.run_tables;

DROP VIEW IF EXISTS __READ__.current_semantic_annotations;
CREATE VIEW __READ__.current_semantic_annotations AS
SELECT r.* FROM __WS__.semantic_annotations r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_slice_definitions;
CREATE VIEW __READ__.current_slice_definitions AS
SELECT r.* FROM __WS__.slice_definitions r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.snippet_usage;
CREATE VIEW __READ__.snippet_usage AS
SELECT * FROM __WS__.snippet_usage;

DROP VIEW IF EXISTS __READ__.sources;
CREATE VIEW __READ__.sources AS
SELECT * FROM __WS__.sources;

DROP VIEW IF EXISTS __READ__.sql_snippets;
CREATE VIEW __READ__.sql_snippets AS
SELECT * FROM __WS__.sql_snippets;

DROP VIEW IF EXISTS __READ__.current_statistical_profiles;
CREATE VIEW __READ__.current_statistical_profiles AS
SELECT r.* FROM __WS__.statistical_profiles r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_statistical_quality_metrics;
CREATE VIEW __READ__.current_statistical_quality_metrics AS
SELECT r.* FROM __WS__.statistical_quality_metrics r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_surrogate_key_intents;
CREATE VIEW __READ__.current_surrogate_key_intents AS
SELECT r.* FROM __WS__.surrogate_key_intents r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_table_entities;
CREATE VIEW __READ__.current_table_entities AS
SELECT r.* FROM __WS__.table_entities r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'catalog'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.tables;
CREATE VIEW __READ__.tables AS
SELECT * FROM __WS__.tables;

DROP VIEW IF EXISTS __READ__.current_temporal_column_profiles;
CREATE VIEW __READ__.current_temporal_column_profiles AS
SELECT r.* FROM __WS__.temporal_column_profiles r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_type_candidates;
CREATE VIEW __READ__.current_type_candidates AS
SELECT r.* FROM __WS__.type_candidates r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_type_decisions;
CREATE VIEW __READ__.current_type_decisions AS
SELECT r.* FROM __WS__.type_decisions r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'generation'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_validation_results;
CREATE VIEW __READ__.current_validation_results AS
SELECT r.* FROM __WS__.validation_results r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'catalog'
    AND h.stage = 'operating_model'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_tables;
CREATE VIEW __READ__.current_tables AS
SELECT t.* FROM __WS__.tables t
WHERE t.layer = 'typed'
  AND EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.target = 'table:' || t.table_id
      AND h.stage = 'generation'
);

DROP VIEW IF EXISTS __READ__.current_columns;
CREATE VIEW __READ__.current_columns AS
SELECT c.* FROM __WS__.columns c
WHERE EXISTS (
  SELECT 1 FROM __WS__.tables t
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || t.table_id
   AND h.stage = 'generation'
  WHERE t.table_id = c.table_id
    AND t.layer = 'typed'
);
