-- GENERATED by `uv run python -m dataraum.storage.dump_ddl` — do not edit.
-- Promoted-read surface (ADR-0008): current_* head-joined views for
-- run-stamped tables + same-named pass-throughs for the rest.
-- Tokenized: __WS__ = raw workspace schema, __READ__ = read schema.
-- Appliers substitute both (engine bootstrap; pull-metadata.sh via sed).

DROP VIEW IF EXISTS __READ__.current_column_drift_summaries;
CREATE VIEW __READ__.current_column_drift_summaries AS
SELECT r.* FROM __WS__.column_drift_summaries r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_column_eligibility;
CREATE VIEW __READ__.current_column_eligibility AS
SELECT r.* FROM __WS__.column_eligibility r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'table:' || r.table_id
    AND h.stage = 'column_eligibility'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.column_slice_profiles;
CREATE VIEW __READ__.column_slice_profiles AS
SELECT * FROM __WS__.column_slice_profiles;

DROP VIEW IF EXISTS __READ__.columns;
CREATE VIEW __READ__.columns AS
SELECT * FROM __WS__.columns;

DROP VIEW IF EXISTS __READ__.config_overlay;
CREATE VIEW __READ__.config_overlay AS
SELECT * FROM __WS__.config_overlay;

DROP VIEW IF EXISTS __READ__.current_derived_columns;
CREATE VIEW __READ__.current_derived_columns AS
SELECT r.* FROM __WS__.derived_columns r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.detected_business_cycles;
CREATE VIEW __READ__.detected_business_cycles AS
SELECT * FROM __WS__.detected_business_cycles;

DROP VIEW IF EXISTS __READ__.current_enriched_views;
CREATE VIEW __READ__.current_enriched_views AS
SELECT r.* FROM __WS__.enriched_views r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_entropy_objects;
CREATE VIEW __READ__.current_entropy_objects AS
SELECT r.*,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'detect' AND h.run_id = r.run_id
      AND h.target = 'table:' || r.table_id
  ) AS via_table_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'detect' AND h.run_id = r.run_id
      AND h.target = 'session:' || r.session_id
  ) AS via_session_head
FROM __WS__.entropy_objects r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.stage = 'detect'
    AND h.run_id = r.run_id
    AND (h.target = 'table:' || r.table_id
      OR h.target = 'session:' || r.session_id)
);

DROP VIEW IF EXISTS __READ__.current_entropy_readiness;
CREATE VIEW __READ__.current_entropy_readiness AS
SELECT r.*,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'detect' AND h.run_id = r.run_id
      AND h.target = 'table:' || r.table_id
  ) AS via_table_head,
  EXISTS (
    SELECT 1 FROM __WS__.metadata_snapshot_head h
    WHERE h.stage = 'detect' AND h.run_id = r.run_id
      AND h.target = 'session:' || r.session_id
  ) AS via_session_head
FROM __WS__.entropy_readiness r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.stage = 'detect'
    AND h.run_id = r.run_id
    AND (h.target = 'table:' || r.table_id
      OR h.target = 'session:' || r.session_id)
);

DROP VIEW IF EXISTS __READ__.fix_ledger;
CREATE VIEW __READ__.fix_ledger AS
SELECT * FROM __WS__.fix_ledger;

DROP VIEW IF EXISTS __READ__.investigation_sessions;
CREATE VIEW __READ__.investigation_sessions AS
SELECT * FROM __WS__.investigation_sessions;

DROP VIEW IF EXISTS __READ__.investigation_steps;
CREATE VIEW __READ__.investigation_steps AS
SELECT * FROM __WS__.investigation_steps;

DROP VIEW IF EXISTS __READ__.current_lifecycle_artifacts;
CREATE VIEW __READ__.current_lifecycle_artifacts AS
SELECT r.* FROM __WS__.lifecycle_artifacts r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'operating_model'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_materialization_recipes;
CREATE VIEW __READ__.current_materialization_recipes AS
SELECT r.* FROM __WS__.materialization_recipes r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'table:' || r.table_id
    AND h.stage = 'typing'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.metadata_snapshot_head;
CREATE VIEW __READ__.metadata_snapshot_head AS
SELECT * FROM __WS__.metadata_snapshot_head;

DROP VIEW IF EXISTS __READ__.query_executions;
CREATE VIEW __READ__.query_executions AS
SELECT * FROM __WS__.query_executions;

DROP VIEW IF EXISTS __READ__.current_relationships;
CREATE VIEW __READ__.current_relationships AS
SELECT r.* FROM __WS__.relationships r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_semantic_annotations;
CREATE VIEW __READ__.current_semantic_annotations AS
SELECT r.* FROM __WS__.semantic_annotations r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'semantic_per_column'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.session_tables;
CREATE VIEW __READ__.session_tables AS
SELECT * FROM __WS__.session_tables;

DROP VIEW IF EXISTS __READ__.current_slice_definitions;
CREATE VIEW __READ__.current_slice_definitions AS
SELECT r.* FROM __WS__.slice_definitions r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_slicing_views;
CREATE VIEW __READ__.current_slicing_views AS
SELECT r.* FROM __WS__.slicing_views r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.snippet_usage;
CREATE VIEW __READ__.snippet_usage AS
SELECT * FROM __WS__.snippet_usage;

DROP VIEW IF EXISTS __READ__.sources;
CREATE VIEW __READ__.sources AS
SELECT * FROM __WS__.sources;

DROP VIEW IF EXISTS __READ__.sql_snippets;
CREATE VIEW __READ__.sql_snippets AS
SELECT * FROM __WS__.sql_snippets;

DROP VIEW IF EXISTS __READ__.current_statistical_profiles;
CREATE VIEW __READ__.current_statistical_profiles AS
SELECT r.* FROM __WS__.statistical_profiles r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'statistics'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_statistical_quality_metrics;
CREATE VIEW __READ__.current_statistical_quality_metrics AS
SELECT r.* FROM __WS__.statistical_quality_metrics r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'statistical_quality'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_table_entities;
CREATE VIEW __READ__.current_table_entities AS
SELECT r.* FROM __WS__.table_entities r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.tables;
CREATE VIEW __READ__.tables AS
SELECT * FROM __WS__.tables;

DROP VIEW IF EXISTS __READ__.current_temporal_column_profiles;
CREATE VIEW __READ__.current_temporal_column_profiles AS
SELECT r.* FROM __WS__.temporal_column_profiles r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'temporal'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_temporal_slice_analyses;
CREATE VIEW __READ__.current_temporal_slice_analyses AS
SELECT r.* FROM __WS__.temporal_slice_analyses r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'detect'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_type_candidates;
CREATE VIEW __READ__.current_type_candidates AS
SELECT r.* FROM __WS__.type_candidates r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'typing'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_type_decisions;
CREATE VIEW __READ__.current_type_decisions AS
SELECT r.* FROM __WS__.type_decisions r
WHERE EXISTS (
  SELECT 1 FROM __WS__.columns c
  JOIN __WS__.metadata_snapshot_head h
    ON h.target = 'table:' || c.table_id
  WHERE c.column_id = r.column_id
    AND h.stage = 'typing'
    AND h.run_id = r.run_id
);

DROP VIEW IF EXISTS __READ__.current_validation_results;
CREATE VIEW __READ__.current_validation_results AS
SELECT r.* FROM __WS__.validation_results r
WHERE EXISTS (
  SELECT 1 FROM __WS__.metadata_snapshot_head h
  WHERE h.target = 'session:' || r.session_id
    AND h.stage = 'operating_model'
    AND h.run_id = r.run_id
);
