-- GENERATED by `uv run python -m dataraum.storage.dump_ddl` — do not edit.
-- Operating-model property graph (ADR-0021): CREATE PROPERTY GRAPH over the
-- promoted-read views (SQL/PGQ, Postgres 19). Element views shape the
-- current_* surface into (source_key, dest_key) relations; the graph binds
-- them with explicit KEY clauses.
-- Tokenized: __WS__ = raw workspace schema, __READ__ = read schema.

DROP PROPERTY GRAPH IF EXISTS __READ__.operating_model;
DROP VIEW IF EXISTS __READ__.og_tables;
DROP VIEW IF EXISTS __READ__.og_columns;
DROP VIEW IF EXISTS __READ__.og_concepts;
DROP VIEW IF EXISTS __READ__.og_grounding;
DROP VIEW IF EXISTS __READ__.og_period_grain;
DROP VIEW IF EXISTS __READ__.og_references;
DROP VIEW IF EXISTS __READ__.og_has_dimension;
DROP VIEW IF EXISTS __READ__.og_derived_from;
DROP VIEW IF EXISTS __READ__.og_concept_edges;
DROP VIEW IF EXISTS __READ__.og_conformed_dimension;
DROP VIEW IF EXISTS __READ__.og_grounded_by;
DROP VIEW IF EXISTS __READ__.og_uses;
DROP VIEW IF EXISTS __READ__.og_temporal_coverage;
DROP VIEW IF EXISTS __READ__.og_rolls_up_to;
DROP VIEW IF EXISTS __READ__.og_period_rolls_up_to;

CREATE VIEW __READ__.og_tables AS
SELECT t.table_id::text AS table_id, t.table_name, t.layer,
       te.table_role, te.detected_entity_type
FROM __READ__.current_tables t
LEFT JOIN __READ__.current_table_entities te ON te.table_id = t.table_id
UNION ALL
SELECT ev.view_table_id::text AS table_id, ev.view_name AS table_name,
       'enriched' AS layer, NULL AS table_role, NULL AS detected_entity_type
FROM __READ__.current_enriched_views ev
WHERE ev.view_table_id IS NOT NULL;

CREATE VIEW __READ__.og_columns AS
SELECT c.column_id::text AS column_id, c.table_id::text AS table_id, c.column_name,
       sa.semantic_role,
       COALESCE(
         CASE mal.pattern WHEN 'per_period' THEN 'flow' WHEN 'cumulative' THEN 'stock' END,
         CASE cc.temporal_behavior WHEN 'additive' THEN 'flow'
                                   WHEN 'point_in_time' THEN 'stock' END
       ) AS materialization,
       COALESCE(mal.event_time_axis_column, declared_anchor.column_name) AS anchor_time_axis
FROM __READ__.current_columns c
LEFT JOIN __READ__.current_semantic_annotations sa ON sa.column_id = c.column_id
LEFT JOIN __READ__.current_column_concepts cc ON cc.column_id = c.column_id
LEFT JOIN __READ__.current_measure_aggregation_lineage mal
       ON mal.measure_column_id = c.column_id
LEFT JOIN __READ__.current_table_entities te ON te.table_id = c.table_id
LEFT JOIN LATERAL (
    SELECT elem->>'column' AS column_name
    FROM json_array_elements(COALESCE(te.time_columns, '[]'::json)) AS elem
    WHERE elem->>'role' = 'event' AND (elem->>'is_anchor')::boolean IS TRUE
    LIMIT 1
  ) declared_anchor ON TRUE
UNION ALL
SELECT ec.column_id::text AS column_id, ec.table_id::text AS table_id, ec.column_name,
       sa.semantic_role,
       COALESCE(
         CASE mal.pattern WHEN 'per_period' THEN 'flow' WHEN 'cumulative' THEN 'stock' END,
         CASE cc.temporal_behavior WHEN 'additive' THEN 'flow'
                                   WHEN 'point_in_time' THEN 'stock' END
       ) AS materialization,
       COALESCE(mal.event_time_axis_column, declared_anchor.column_name) AS anchor_time_axis
FROM __READ__.current_enriched_columns ec
LEFT JOIN __READ__.current_semantic_annotations sa ON sa.column_id = ec.source_column_id
LEFT JOIN __READ__.current_column_concepts cc ON cc.column_id = ec.source_column_id
LEFT JOIN __READ__.current_measure_aggregation_lineage mal
       ON mal.measure_column_id = ec.source_column_id
LEFT JOIN __READ__.current_columns src ON src.column_id = ec.source_column_id
LEFT JOIN __READ__.current_table_entities te ON te.table_id = src.table_id
LEFT JOIN LATERAL (
    SELECT elem->>'column' AS column_name
    FROM json_array_elements(COALESCE(te.time_columns, '[]'::json)) AS elem
    WHERE elem->>'role' = 'event' AND (elem->>'is_anchor')::boolean IS TRUE
    LIMIT 1
  ) declared_anchor ON TRUE;

CREATE VIEW __READ__.og_concepts AS
SELECT concept_id::text AS concept_id, vertical, name, kind, ordering
FROM __READ__.concepts
WHERE superseded_at IS NULL;

CREATE VIEW __READ__.og_grounding AS
SELECT g.snippet_id::text AS snippet_id,
       g.concept, g.statement, g.aggregation, g.description,
       g.relation, g.select_expr, g.where_predicates, g.failed
FROM __READ__.current_groundings g;

CREATE VIEW __READ__.og_period_grain AS
SELECT g.grain::text AS grain, g.ordinal,
       COALESCE(wc.fiscal_year_start_month, 1) AS fiscal_year_start_month,
       CASE WHEN wc.fiscal_year_start_month IS NULL THEN 'default'
            ELSE 'declared' END AS calendar_source
FROM (VALUES ('day', 0), ('month', 1), ('quarter', 2), ('year', 3))
       AS g(grain, ordinal)
LEFT JOIN __READ__.workspace_calendar wc ON TRUE;

CREATE VIEW __READ__.og_references AS
SELECT relationship_id::text AS relationship_id,
       from_table_id::text AS from_table_id, to_table_id::text AS to_table_id,
       from_column_id, to_column_id, cardinality, relationship_type,
       confidence, confirmation_source
FROM __READ__.current_relationships r
WHERE r.relationship_type IN ('foreign_key', 'hierarchy')
  AND r.detection_method != 'candidate';

CREATE VIEW __READ__.og_has_dimension AS
SELECT slice_id::text AS slice_id, table_id::text AS table_id,
       column_id::text AS column_id, column_name, slice_type, slice_priority,
       dimension_table_id::text AS dimension_table_id,
       dimension_attribute, fk_role
FROM __READ__.current_slice_definitions;

CREATE VIEW __READ__.og_derived_from AS
SELECT (ev.view_id || '_fact')::text AS edge_key,
       ev.view_table_id::text AS view_table_id,
       ev.fact_table_id::text AS base_table_id, 'fact' AS base_role
FROM __READ__.current_enriched_views ev
WHERE ev.view_table_id IS NOT NULL
UNION ALL
SELECT DISTINCT (ev.view_id || '_dim_' || dt.value)::text AS edge_key,
       ev.view_table_id::text AS view_table_id,
       dt.value AS base_table_id, 'dimension' AS base_role
FROM __READ__.current_enriched_views ev
CROSS JOIN LATERAL json_array_elements_text(
     COALESCE(ev.dimension_table_ids, '[]'::json)) AS dt(value)
WHERE ev.view_table_id IS NOT NULL;

CREATE VIEW __READ__.og_concept_edges AS
SELECT e.edge_id::text AS edge_id,
       cf.concept_id::text AS from_concept_id,
       ct.concept_id::text AS to_concept_id,
       e.predicate, e.tolerance
FROM __READ__.concept_edges e
JOIN __READ__.concepts cf
  ON cf.vertical = e.vertical AND cf.name = e.from_concept
 AND cf.superseded_at IS NULL
JOIN __READ__.concepts ct
  ON ct.vertical = e.vertical AND ct.name = e.to_concept
 AND ct.superseded_at IS NULL
WHERE e.superseded_at IS NULL;

CREATE VIEW __READ__.og_conformed_dimension AS
SELECT (s1.slice_id || '_' || s2.slice_id)::text AS edge_key,
       s1.table_id::text AS from_table_id, s2.table_id::text AS to_table_id,
       s1.dimension_table_id::text AS dimension_table_id,
       s1.dimension_attribute AS dimension_attribute
FROM __READ__.current_slice_definitions s1
JOIN __READ__.current_slice_definitions s2
  ON s1.dimension_table_id = s2.dimension_table_id
 AND COALESCE(s1.dimension_attribute, '') = COALESCE(s2.dimension_attribute, '')
 AND s1.table_id <> s2.table_id
WHERE s1.dimension_table_id IS NOT NULL;

CREATE VIEW __READ__.og_grounded_by AS
SELECT (c.concept_id || '_' || g.snippet_id)::text AS edge_key,
       c.concept_id::text AS concept_id,
       g.snippet_id::text AS snippet_id,
       g.concept
FROM __READ__.current_groundings g
JOIN __READ__.concepts c
  ON c.name = g.concept AND c.superseded_at IS NULL;

CREATE VIEW __READ__.og_uses AS
SELECT DISTINCT ON (g.snippet_id, col.column_id)
       (g.snippet_id || '_' || col.column_id)::text AS edge_key,
       g.snippet_id::text AS snippet_id,
       col.column_id::text AS column_id,
       u.role
FROM __READ__.current_groundings g
CROSS JOIN LATERAL json_each(
     COALESCE(g.provenance->'column_mappings_basis', '{}'::json)
     ) AS b(concept, entry)
CROSS JOIN LATERAL (
  SELECT m.value AS column_name, 'measure' AS role
  FROM json_array_elements_text(
       COALESCE(b.entry->'measure_columns', '[]'::json)) m(value)
  UNION ALL
  SELECT f.value, 'filter'
  FROM json_array_elements_text(
       COALESCE(b.entry->'filter_columns', '[]'::json)) f(value)
) u
CROSS JOIN LATERAL (
  SELECT ec.column_id
  FROM __READ__.current_enriched_views ev
  JOIN __READ__.current_enriched_columns ec
    ON ec.table_id = ev.view_table_id AND ec.column_name = u.column_name
  WHERE ev.view_name = g.relation
  UNION ALL
  SELECT tc.column_id
  FROM __READ__.current_tables t
  JOIN __READ__.current_columns tc
    ON tc.table_id = t.table_id AND tc.column_name = u.column_name
  WHERE (t.table_name = g.relation OR t.duckdb_path = g.relation)
    AND NOT EXISTS (
      SELECT 1 FROM __READ__.current_enriched_views ev2
      WHERE ev2.view_name = g.relation)
) col
WHERE NOT g.failed
ORDER BY g.snippet_id, col.column_id,
         CASE u.role WHEN 'measure' THEN 0 ELSE 1 END;

CREATE VIEW __READ__.og_temporal_coverage AS
SELECT DISTINCT ON (te.table_id, col.column_id)
       (te.table_id || '_' || col.column_id)::text AS coverage_key,
       te.table_id::text AS table_id, col.column_id::text AS column_id,
       col.column_name, tc.role, tc.aspect, tc.declared_anchor,
       tp.min_timestamp AS observed_min, tp.max_timestamp AS observed_max,
       tp.span_days, tp.detected_granularity AS observed_grain,
       tp.completeness_ratio, tp.expected_periods, tp.actual_periods,
       tp.gap_count, tp.is_stale, tp.last_period_complete
FROM __READ__.current_table_entities te
CROSS JOIN LATERAL (
    SELECT elem->>'column' AS column_name, elem->>'role' AS role,
           elem->>'aspect' AS aspect,
           (elem->>'is_anchor')::boolean AS declared_anchor
    FROM json_array_elements(COALESCE(te.time_columns, '[]'::json)) AS elem
  ) tc
JOIN __READ__.current_columns col
  ON col.table_id = te.table_id AND col.column_name = tc.column_name
LEFT JOIN __READ__.current_temporal_column_profiles tp
  ON tp.column_id = col.column_id
ORDER BY te.table_id, col.column_id, tc.declared_anchor DESC NULLS LAST,
         tc.role, tc.aspect, tc.column_name;

CREATE VIEW __READ__.og_rolls_up_to AS
SELECT (h.hierarchy_id || '_' || fine.lvl || '_' || coarse.lvl)::text
         AS edge_key,
       fine.col_id::text AS from_column_id,
       coarse.col_id::text AS to_column_id,
       h.hierarchy_id::text AS hierarchy_id,
       fine.lvl AS from_level, coarse.lvl AS to_level
FROM __READ__.current_dimension_hierarchies h
CROSS JOIN LATERAL (
    SELECT m->>'column_id' AS col_id, (m->>'level')::int AS lvl
    FROM json_array_elements(h.members) AS m
  ) fine
CROSS JOIN LATERAL (
    SELECT m->>'column_id' AS col_id, (m->>'level')::int AS lvl
    FROM json_array_elements(h.members) AS m
  ) coarse
WHERE h.kind = 'drilldown'
  AND coarse.lvl = fine.lvl - 1
  AND fine.col_id <> '' AND coarse.col_id <> '';

CREATE VIEW __READ__.og_period_rolls_up_to AS
SELECT (l.from_grain || '_' || l.to_grain)::text AS edge_key,
       l.from_grain::text AS from_grain, l.to_grain::text AS to_grain
FROM (VALUES ('day', 'month'), ('month', 'quarter'), ('quarter', 'year'))
       AS l(from_grain, to_grain);

CREATE PROPERTY GRAPH __READ__.operating_model
  VERTEX TABLES (
    __READ__.og_tables KEY (table_id) LABEL table_node
      PROPERTIES (table_id, table_name, layer, table_role, detected_entity_type),
    __READ__.og_columns KEY (column_id) LABEL column_node
      PROPERTIES (column_id, table_id, column_name, semantic_role, materialization,
                  anchor_time_axis),
    __READ__.og_concepts KEY (concept_id) LABEL concept_node
      PROPERTIES (concept_id, vertical, name, kind, ordering),
    __READ__.og_grounding KEY (snippet_id) LABEL grounding_node
      PROPERTIES (snippet_id, concept, statement, aggregation,
                  relation, select_expr, where_predicates, description, failed),
    __READ__.og_period_grain KEY (grain) LABEL period_grain
      PROPERTIES (grain, ordinal, fiscal_year_start_month, calendar_source)
  )
  EDGE TABLES (
    __READ__.og_references KEY (relationship_id)
      SOURCE KEY (from_table_id) REFERENCES og_tables (table_id)
      DESTINATION KEY (to_table_id) REFERENCES og_tables (table_id)
      LABEL refs
      PROPERTIES (cardinality, relationship_type, confidence, confirmation_source,
                  from_column_id, to_column_id),
    __READ__.og_has_dimension KEY (slice_id)
      SOURCE KEY (table_id) REFERENCES og_tables (table_id)
      DESTINATION KEY (column_id) REFERENCES og_columns (column_id)
      LABEL has_dimension
      PROPERTIES (column_name, slice_type, slice_priority,
                  dimension_table_id, dimension_attribute, fk_role),
    __READ__.og_derived_from KEY (edge_key)
      SOURCE KEY (view_table_id) REFERENCES og_tables (table_id)
      DESTINATION KEY (base_table_id) REFERENCES og_tables (table_id)
      LABEL derived_from
      PROPERTIES (base_role),
    __READ__.og_concept_edges KEY (edge_id)
      SOURCE KEY (from_concept_id) REFERENCES og_concepts (concept_id)
      DESTINATION KEY (to_concept_id) REFERENCES og_concepts (concept_id)
      LABEL concept_edge
      PROPERTIES (predicate, tolerance),
    __READ__.og_conformed_dimension KEY (edge_key)
      SOURCE KEY (from_table_id) REFERENCES og_tables (table_id)
      DESTINATION KEY (to_table_id) REFERENCES og_tables (table_id)
      LABEL conformed_dimension
      PROPERTIES (dimension_table_id, dimension_attribute),
    __READ__.og_grounded_by KEY (edge_key)
      SOURCE KEY (concept_id) REFERENCES og_concepts (concept_id)
      DESTINATION KEY (snippet_id) REFERENCES og_grounding (snippet_id)
      LABEL grounded_by
      PROPERTIES (concept),
    __READ__.og_uses KEY (edge_key)
      SOURCE KEY (snippet_id) REFERENCES og_grounding (snippet_id)
      DESTINATION KEY (column_id) REFERENCES og_columns (column_id)
      LABEL uses
      PROPERTIES (role),
    __READ__.og_temporal_coverage KEY (coverage_key)
      SOURCE KEY (table_id) REFERENCES og_tables (table_id)
      DESTINATION KEY (column_id) REFERENCES og_columns (column_id)
      LABEL temporal_coverage
      PROPERTIES (column_name, role, aspect, declared_anchor, observed_min,
                  observed_max, span_days, observed_grain, completeness_ratio,
                  expected_periods, actual_periods, gap_count, is_stale,
                  last_period_complete),
    __READ__.og_rolls_up_to KEY (edge_key)
      SOURCE KEY (from_column_id) REFERENCES og_columns (column_id)
      DESTINATION KEY (to_column_id) REFERENCES og_columns (column_id)
      LABEL rolls_up_to
      PROPERTIES (hierarchy_id, from_level, to_level),
    __READ__.og_period_rolls_up_to KEY (edge_key)
      SOURCE KEY (from_grain) REFERENCES og_period_grain (grain)
      DESTINATION KEY (to_grain) REFERENCES og_period_grain (grain)
      LABEL period_rolls_up_to
      PROPERTIES (from_grain, to_grain)
  );
