-- GENERATED by `uv run python -m dataraum.storage.dump_ddl` — do not edit.
-- Source of truth: the SQLAlchemy models (storage.base.load_all_models).
-- Schema-less on purpose: apply with search_path set to the target ws_<id>.

CREATE TABLE config_overlay (
	overlay_id VARCHAR NOT NULL, 
	session_id VARCHAR, 
	type VARCHAR NOT NULL, 
	payload JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	superseded_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT pk_config_overlay PRIMARY KEY (overlay_id)
);

CREATE INDEX idx_config_overlay_active ON config_overlay (superseded_at, type);

CREATE TABLE investigation_sessions (
	session_id VARCHAR NOT NULL, 
	status VARCHAR NOT NULL, 
	started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	ended_at TIMESTAMP WITHOUT TIME ZONE, 
	duration_seconds FLOAT, 
	intent VARCHAR NOT NULL, 
	contract VARCHAR, 
	vertical VARCHAR, 
	outcome_summary VARCHAR, 
	outcome_payload JSON, 
	step_count INTEGER NOT NULL, 
	CONSTRAINT pk_investigation_sessions PRIMARY KEY (session_id)
);

CREATE TABLE metadata_snapshot_head (
	head_id VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	stage VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	promoted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	version INTEGER NOT NULL, 
	CONSTRAINT pk_metadata_snapshot_head PRIMARY KEY (head_id), 
	CONSTRAINT uq_snapshot_head_target_stage UNIQUE (target, stage)
);

CREATE TABLE sources (
	source_id VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	source_type VARCHAR NOT NULL, 
	connection_config JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	status VARCHAR, 
	stage VARCHAR, 
	backend VARCHAR, 
	discovered_schema JSON, 
	archived_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT pk_sources PRIMARY KEY (source_id), 
	CONSTRAINT uq_sources_name UNIQUE (name)
);

CREATE TABLE column_drift_summaries (
	id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	slice_table_name VARCHAR(255) NOT NULL, 
	column_name VARCHAR(255) NOT NULL, 
	time_column VARCHAR(255) NOT NULL, 
	max_js_divergence FLOAT NOT NULL, 
	mean_js_divergence FLOAT NOT NULL, 
	periods_analyzed INTEGER NOT NULL, 
	periods_with_drift INTEGER NOT NULL, 
	drift_evidence_json JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_column_drift_summaries PRIMARY KEY (id), 
	CONSTRAINT uq_drift_slice_column_run UNIQUE (slice_table_name, column_name, run_id), 
	CONSTRAINT fk_column_drift_summaries_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id)
);

CREATE INDEX ix_column_drift_summaries_column_name ON column_drift_summaries (column_name);

CREATE INDEX ix_column_drift_summaries_session_id ON column_drift_summaries (session_id);

CREATE INDEX ix_column_drift_summaries_slice_table_name ON column_drift_summaries (slice_table_name);

CREATE TABLE detected_business_cycles (
	cycle_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	cycle_name VARCHAR NOT NULL, 
	cycle_type VARCHAR NOT NULL, 
	canonical_type VARCHAR, 
	is_known_type BOOLEAN NOT NULL, 
	description TEXT, 
	business_value VARCHAR NOT NULL, 
	confidence FLOAT NOT NULL, 
	tables_involved JSON NOT NULL, 
	stages JSON NOT NULL, 
	entity_flows JSON NOT NULL, 
	status_table VARCHAR, 
	status_column VARCHAR, 
	completion_value VARCHAR, 
	total_records INTEGER, 
	completed_cycles INTEGER, 
	completion_rate FLOAT, 
	evidence JSON NOT NULL, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_detected_business_cycles PRIMARY KEY (cycle_id), 
	CONSTRAINT fk_detected_business_cycles_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_detected_business_cycles_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id) ON DELETE CASCADE
);

CREATE INDEX idx_detected_cycles_source ON detected_business_cycles (source_id);

CREATE INDEX ix_detected_business_cycles_session_id ON detected_business_cycles (session_id);

CREATE TABLE fix_ledger (
	fix_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	action_name VARCHAR NOT NULL, 
	table_name VARCHAR NOT NULL, 
	column_name VARCHAR, 
	user_input VARCHAR NOT NULL, 
	interpretation VARCHAR NOT NULL, 
	status VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	superseded_at TIMESTAMP WITHOUT TIME ZONE, 
	superseded_by VARCHAR, 
	CONSTRAINT pk_fix_ledger PRIMARY KEY (fix_id), 
	CONSTRAINT fk_fix_ledger_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_fix_ledger_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id), 
	CONSTRAINT fk_fix_ledger_superseded_by_fix_ledger FOREIGN KEY(superseded_by) REFERENCES fix_ledger (fix_id)
);

CREATE INDEX idx_fix_ledger_scope ON fix_ledger (source_id, action_name, table_name, column_name);

CREATE INDEX idx_fix_ledger_source ON fix_ledger (source_id);

CREATE INDEX ix_fix_ledger_session_id ON fix_ledger (session_id);

CREATE TABLE investigation_steps (
	step_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	ordinal INTEGER NOT NULL, 
	tool_name VARCHAR NOT NULL, 
	arguments JSON NOT NULL, 
	status VARCHAR NOT NULL, 
	result_summary VARCHAR, 
	error VARCHAR, 
	started_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	duration_seconds FLOAT NOT NULL, 
	target VARCHAR, 
	dimension VARCHAR, 
	CONSTRAINT pk_investigation_steps PRIMARY KEY (step_id), 
	CONSTRAINT fk_investigation_steps_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id) ON DELETE CASCADE
);

CREATE INDEX idx_inv_step_target ON investigation_steps (target);

CREATE INDEX idx_inv_step_tool ON investigation_steps (tool_name);

CREATE INDEX ix_investigation_steps_session_id ON investigation_steps (session_id);

CREATE TABLE query_executions (
	execution_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	question TEXT NOT NULL, 
	sql_executed TEXT NOT NULL, 
	executed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	success BOOLEAN NOT NULL, 
	row_count INTEGER, 
	error_message TEXT, 
	confidence_level VARCHAR NOT NULL, 
	contract_name VARCHAR, 
	entropy_action VARCHAR, 
	CONSTRAINT pk_query_executions PRIMARY KEY (execution_id), 
	CONSTRAINT fk_query_executions_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_query_executions_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id) ON DELETE CASCADE
);

CREATE INDEX ix_query_executions_session_id ON query_executions (session_id);

CREATE INDEX ix_query_executions_source_id ON query_executions (source_id);

CREATE TABLE sql_snippets (
	snippet_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	snippet_type VARCHAR NOT NULL, 
	standard_field VARCHAR, 
	statement VARCHAR, 
	aggregation VARCHAR, 
	schema_mapping_id VARCHAR NOT NULL, 
	parameter_value VARCHAR, 
	normalized_expression VARCHAR, 
	input_fields JSON, 
	sql TEXT NOT NULL, 
	description TEXT NOT NULL, 
	column_mappings JSON NOT NULL, 
	source VARCHAR NOT NULL, 
	llm_model VARCHAR, 
	provenance JSON, 
	execution_count INTEGER NOT NULL, 
	failure_count INTEGER NOT NULL, 
	last_used_at TIMESTAMP WITHOUT TIME ZONE, 
	column_hash VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_sql_snippets PRIMARY KEY (snippet_id), 
	CONSTRAINT uq_snippet_semantic_key UNIQUE (snippet_type, standard_field, statement, aggregation, schema_mapping_id, parameter_value), 
	CONSTRAINT fk_sql_snippets_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id)
);

CREATE INDEX ix_sql_snippets_normalized_expression ON sql_snippets (normalized_expression);

CREATE INDEX ix_sql_snippets_schema_mapping_id ON sql_snippets (schema_mapping_id);

CREATE INDEX ix_sql_snippets_session_id ON sql_snippets (session_id);

CREATE INDEX ix_sql_snippets_snippet_type ON sql_snippets (snippet_type);

CREATE INDEX ix_sql_snippets_standard_field ON sql_snippets (standard_field);

CREATE TABLE tables (
	table_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	table_name VARCHAR NOT NULL, 
	layer VARCHAR NOT NULL, 
	duckdb_path VARCHAR, 
	row_count INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_profiled_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT pk_tables PRIMARY KEY (table_id), 
	CONSTRAINT uq_source_table_layer UNIQUE (source_id, table_name, layer), 
	CONSTRAINT fk_tables_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id)
);

CREATE INDEX idx_tables_source ON tables (source_id);

CREATE TABLE temporal_slice_analyses (
	id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	slice_table_name VARCHAR(255) NOT NULL, 
	time_column VARCHAR(255) NOT NULL, 
	period_label VARCHAR(50) NOT NULL, 
	period_start DATE NOT NULL, 
	period_end DATE NOT NULL, 
	row_count INTEGER, 
	expected_days INTEGER, 
	observed_days INTEGER, 
	coverage_ratio FLOAT, 
	is_complete INTEGER, 
	has_early_cutoff INTEGER, 
	days_missing_at_end INTEGER, 
	last_day_ratio FLOAT, 
	z_score FLOAT, 
	rolling_avg FLOAT, 
	rolling_std FLOAT, 
	is_volume_anomaly INTEGER, 
	anomaly_type VARCHAR(20), 
	period_over_period_change FLOAT, 
	issues_json JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_temporal_slice_analyses PRIMARY KEY (id), 
	CONSTRAINT fk_temporal_slice_analyses_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id)
);

CREATE INDEX ix_temporal_slice_analyses_period_label ON temporal_slice_analyses (period_label);

CREATE INDEX ix_temporal_slice_analyses_session_id ON temporal_slice_analyses (session_id);

CREATE INDEX ix_temporal_slice_analyses_slice_table_name ON temporal_slice_analyses (slice_table_name);

CREATE TABLE validation_results (
	result_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	validation_id VARCHAR NOT NULL, 
	table_ids JSON NOT NULL, 
	status VARCHAR NOT NULL, 
	severity VARCHAR NOT NULL, 
	passed BOOLEAN NOT NULL, 
	message TEXT, 
	executed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	sql_used TEXT, 
	details JSON, 
	CONSTRAINT pk_validation_results PRIMARY KEY (result_id), 
	CONSTRAINT fk_validation_results_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id)
);

CREATE INDEX ix_validation_results_session_id ON validation_results (session_id);

CREATE INDEX ix_validation_results_validation_id ON validation_results (validation_id);

CREATE TABLE column_eligibility (
	eligibility_id VARCHAR(36) NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR(36) NOT NULL, 
	table_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	column_name VARCHAR NOT NULL, 
	table_name VARCHAR NOT NULL, 
	resolved_type VARCHAR, 
	status VARCHAR(20) NOT NULL, 
	triggered_rule VARCHAR(50), 
	reason TEXT, 
	metrics_snapshot JSON NOT NULL, 
	config_version VARCHAR(20) NOT NULL, 
	evaluated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_column_eligibility PRIMARY KEY (eligibility_id), 
	CONSTRAINT uq_column_eligibility_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_column_eligibility_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_column_eligibility_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_column_eligibility_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id) ON DELETE CASCADE
);

CREATE INDEX idx_eligibility_column ON column_eligibility (column_id);

CREATE INDEX idx_eligibility_source ON column_eligibility (source_id);

CREATE INDEX idx_eligibility_status ON column_eligibility (status);

CREATE INDEX idx_eligibility_table ON column_eligibility (table_id);

CREATE INDEX ix_column_eligibility_session_id ON column_eligibility (session_id);

CREATE TABLE columns (
	column_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	column_name VARCHAR NOT NULL, 
	original_name VARCHAR, 
	column_position INTEGER NOT NULL, 
	raw_type VARCHAR, 
	resolved_type VARCHAR, 
	CONSTRAINT pk_columns PRIMARY KEY (column_id), 
	CONSTRAINT uq_table_column UNIQUE (table_id, column_name), 
	CONSTRAINT fk_columns_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE
);

CREATE INDEX idx_columns_table ON columns (table_id);

CREATE TABLE enriched_views (
	view_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	fact_table_id VARCHAR NOT NULL, 
	view_table_id VARCHAR, 
	view_name VARCHAR NOT NULL, 
	run_id VARCHAR, 
	relationship_ids JSON, 
	dimension_table_ids JSON, 
	dimension_columns JSON, 
	is_grain_verified BOOLEAN NOT NULL, 
	evidence JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_enriched_views PRIMARY KEY (view_id), 
	CONSTRAINT uq_enriched_view_fact_table UNIQUE (fact_table_id), 
	CONSTRAINT fk_enriched_views_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_enriched_views_fact_table_id_tables FOREIGN KEY(fact_table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_enriched_views_view_table_id_tables FOREIGN KEY(view_table_id) REFERENCES tables (table_id) ON DELETE SET NULL
);

CREATE INDEX ix_enriched_views_run_id ON enriched_views (run_id);

CREATE INDEX ix_enriched_views_session_id ON enriched_views (session_id);

CREATE TABLE materialization_recipes (
	recipe_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	layer VARCHAR NOT NULL, 
	run_id VARCHAR, 
	target_fqn VARCHAR NOT NULL, 
	ddl VARCHAR NOT NULL, 
	depends_on JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_materialization_recipes PRIMARY KEY (recipe_id), 
	CONSTRAINT uq_materialization_recipe_table_layer_run UNIQUE (table_id, layer, run_id), 
	CONSTRAINT fk_materialization_recipes_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_materialization_recipes_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE
);

CREATE INDEX idx_materialization_recipes_table ON materialization_recipes (table_id);

CREATE INDEX ix_materialization_recipes_session_id ON materialization_recipes (session_id);

CREATE TABLE session_tables (
	session_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	CONSTRAINT pk_session_tables PRIMARY KEY (session_id, table_id), 
	CONSTRAINT fk_session_tables_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id) ON DELETE CASCADE, 
	CONSTRAINT fk_session_tables_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE
);

CREATE INDEX idx_session_tables_table ON session_tables (table_id);

CREATE TABLE slicing_views (
	view_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	fact_table_id VARCHAR NOT NULL, 
	view_name VARCHAR NOT NULL, 
	run_id VARCHAR, 
	slice_definition_ids JSON, 
	slice_columns JSON, 
	is_grain_verified BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_slicing_views PRIMARY KEY (view_id), 
	CONSTRAINT uq_slicing_view_fact_table UNIQUE (fact_table_id), 
	CONSTRAINT fk_slicing_views_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_slicing_views_fact_table_id_tables FOREIGN KEY(fact_table_id) REFERENCES tables (table_id) ON DELETE CASCADE
);

CREATE INDEX ix_slicing_views_run_id ON slicing_views (run_id);

CREATE INDEX ix_slicing_views_session_id ON slicing_views (session_id);

CREATE TABLE snippet_usage (
	usage_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	execution_id VARCHAR NOT NULL, 
	execution_type VARCHAR NOT NULL, 
	snippet_id VARCHAR, 
	usage_type VARCHAR NOT NULL, 
	match_confidence FLOAT NOT NULL, 
	sql_match_ratio FLOAT NOT NULL, 
	step_id VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_snippet_usage PRIMARY KEY (usage_id), 
	CONSTRAINT fk_snippet_usage_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_snippet_usage_snippet_id_sql_snippets FOREIGN KEY(snippet_id) REFERENCES sql_snippets (snippet_id) ON DELETE CASCADE
);

CREATE INDEX ix_snippet_usage_execution_id ON snippet_usage (execution_id);

CREATE INDEX ix_snippet_usage_session_id ON snippet_usage (session_id);

CREATE INDEX ix_snippet_usage_snippet_id ON snippet_usage (snippet_id);

CREATE TABLE table_entities (
	entity_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	detected_entity_type VARCHAR NOT NULL, 
	description TEXT, 
	confidence FLOAT, 
	evidence JSON, 
	grain_columns JSON, 
	is_fact_table BOOLEAN, 
	is_dimension_table BOOLEAN, 
	time_column VARCHAR, 
	detection_source VARCHAR, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_table_entities PRIMARY KEY (entity_id), 
	CONSTRAINT uq_table_entity_table_run UNIQUE (table_id, run_id), 
	CONSTRAINT fk_table_entities_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_table_entities_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE
);

CREATE INDEX ix_table_entities_session_id ON table_entities (session_id);

CREATE TABLE column_slice_profiles (
	profile_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	source_column_id VARCHAR NOT NULL, 
	slice_column_id VARCHAR NOT NULL, 
	source_table_name VARCHAR NOT NULL, 
	column_name VARCHAR NOT NULL, 
	slice_column_name VARCHAR NOT NULL, 
	slice_value VARCHAR NOT NULL, 
	row_count INTEGER NOT NULL, 
	null_ratio FLOAT, 
	distinct_count INTEGER, 
	quality_score FLOAT, 
	has_issues INTEGER NOT NULL, 
	issue_count INTEGER NOT NULL, 
	profile_data JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_column_slice_profiles PRIMARY KEY (profile_id), 
	CONSTRAINT fk_column_slice_profiles_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_column_slice_profiles_source_column_id_columns FOREIGN KEY(source_column_id) REFERENCES columns (column_id) ON DELETE CASCADE, 
	CONSTRAINT fk_column_slice_profiles_slice_column_id_columns FOREIGN KEY(slice_column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_slice_profiles_lookup ON column_slice_profiles (source_column_id, slice_column_id, slice_value);

CREATE INDEX idx_slice_profiles_slice_column ON column_slice_profiles (slice_column_id);

CREATE INDEX idx_slice_profiles_source_column ON column_slice_profiles (source_column_id);

CREATE INDEX ix_column_slice_profiles_session_id ON column_slice_profiles (session_id);

CREATE TABLE derived_columns (
	derived_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	table_id VARCHAR NOT NULL, 
	derived_column_id VARCHAR NOT NULL, 
	source_column_ids JSON NOT NULL, 
	derivation_type VARCHAR NOT NULL, 
	formula VARCHAR NOT NULL, 
	match_rate FLOAT NOT NULL, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	total_rows INTEGER NOT NULL, 
	matching_rows INTEGER NOT NULL, 
	mismatch_examples JSON, 
	CONSTRAINT pk_derived_columns PRIMARY KEY (derived_id), 
	CONSTRAINT fk_derived_columns_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_derived_columns_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_derived_columns_derived_column_id_columns FOREIGN KEY(derived_column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_derived_column ON derived_columns (derived_column_id);

CREATE INDEX idx_derived_table ON derived_columns (table_id);

CREATE INDEX ix_derived_columns_session_id ON derived_columns (session_id);

CREATE TABLE entropy_objects (
	object_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	layer VARCHAR NOT NULL, 
	dimension VARCHAR NOT NULL, 
	sub_dimension VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	table_id VARCHAR, 
	column_id VARCHAR, 
	run_id VARCHAR, 
	score FLOAT NOT NULL, 
	evidence JSONB, 
	detector_id VARCHAR NOT NULL, 
	source_analysis_ids JSONB, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_entropy_objects PRIMARY KEY (object_id), 
	CONSTRAINT fk_entropy_objects_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_entropy_objects_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_entropy_objects_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_entropy_column ON entropy_objects (column_id);

CREATE INDEX idx_entropy_layer_dimension ON entropy_objects (layer, dimension);

CREATE INDEX idx_entropy_score ON entropy_objects (score);

CREATE INDEX idx_entropy_table ON entropy_objects (table_id);

CREATE INDEX idx_entropy_target ON entropy_objects (target);

CREATE INDEX ix_entropy_objects_session_id ON entropy_objects (session_id);

CREATE TABLE entropy_readiness (
	readiness_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	table_id VARCHAR, 
	column_id VARCHAR, 
	run_id VARCHAR, 
	band VARCHAR NOT NULL, 
	worst_intent_risk FLOAT NOT NULL, 
	intents JSONB, 
	top_drivers JSONB, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_entropy_readiness PRIMARY KEY (readiness_id), 
	CONSTRAINT fk_entropy_readiness_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_entropy_readiness_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_entropy_readiness_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_readiness_column ON entropy_readiness (column_id);

CREATE INDEX idx_readiness_table ON entropy_readiness (table_id);

CREATE INDEX idx_readiness_target ON entropy_readiness (target);

CREATE INDEX ix_entropy_readiness_session_id ON entropy_readiness (session_id);

CREATE TABLE relationships (
	relationship_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	from_table_id VARCHAR NOT NULL, 
	from_column_id VARCHAR NOT NULL, 
	to_table_id VARCHAR NOT NULL, 
	to_column_id VARCHAR NOT NULL, 
	relationship_type VARCHAR NOT NULL, 
	cardinality VARCHAR, 
	confidence FLOAT NOT NULL, 
	detection_method VARCHAR, 
	evidence JSON, 
	is_confirmed BOOLEAN NOT NULL, 
	confirmed_at TIMESTAMP WITHOUT TIME ZONE, 
	confirmed_by VARCHAR, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_relationships PRIMARY KEY (relationship_id), 
	CONSTRAINT uq_relationship_columns_method UNIQUE (session_id, run_id, from_column_id, to_column_id, detection_method), 
	CONSTRAINT fk_relationships_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_relationships_from_table_id_tables FOREIGN KEY(from_table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_relationships_from_column_id_columns FOREIGN KEY(from_column_id) REFERENCES columns (column_id) ON DELETE CASCADE, 
	CONSTRAINT fk_relationships_to_table_id_tables FOREIGN KEY(to_table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_relationships_to_column_id_columns FOREIGN KEY(to_column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_relationships_from ON relationships (from_table_id);

CREATE INDEX idx_relationships_from_column ON relationships (from_column_id);

CREATE INDEX idx_relationships_from_table_column ON relationships (from_table_id, from_column_id);

CREATE INDEX idx_relationships_to ON relationships (to_table_id);

CREATE INDEX idx_relationships_to_column ON relationships (to_column_id);

CREATE INDEX idx_relationships_to_table_column ON relationships (to_table_id, to_column_id);

CREATE INDEX ix_relationships_run_id ON relationships (run_id);

CREATE INDEX ix_relationships_session_id ON relationships (session_id);

CREATE TABLE semantic_annotations (
	annotation_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	semantic_role VARCHAR, 
	entity_type VARCHAR, 
	business_name VARCHAR, 
	business_description TEXT, 
	business_concept VARCHAR, 
	temporal_behavior VARCHAR, 
	unit_source_column VARCHAR, 
	annotation_source VARCHAR, 
	annotated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	annotated_by VARCHAR, 
	confidence FLOAT, 
	CONSTRAINT pk_semantic_annotations PRIMARY KEY (annotation_id), 
	CONSTRAINT uq_column_semantic_annotation UNIQUE (column_id, run_id), 
	CONSTRAINT fk_semantic_annotations_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_semantic_annotations_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX ix_semantic_annotations_session_id ON semantic_annotations (session_id);

CREATE TABLE slice_definitions (
	slice_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	table_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	column_name VARCHAR, 
	slice_priority INTEGER NOT NULL, 
	slice_type VARCHAR NOT NULL, 
	distinct_values JSON, 
	value_count INTEGER, 
	reasoning TEXT, 
	business_context TEXT, 
	confidence FLOAT, 
	sql_template TEXT, 
	detection_source VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_slice_definitions PRIMARY KEY (slice_id), 
	CONSTRAINT fk_slice_definitions_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_slice_definitions_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE, 
	CONSTRAINT fk_slice_definitions_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_slice_definitions_column ON slice_definitions (column_id);

CREATE INDEX idx_slice_definitions_table ON slice_definitions (table_id);

CREATE INDEX ix_slice_definitions_session_id ON slice_definitions (session_id);

CREATE TABLE statistical_profiles (
	profile_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	profiled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	layer VARCHAR NOT NULL, 
	total_count INTEGER NOT NULL, 
	null_count INTEGER NOT NULL, 
	distinct_count INTEGER, 
	null_ratio FLOAT, 
	cardinality_ratio FLOAT, 
	is_unique INTEGER, 
	is_numeric INTEGER, 
	profile_data JSON NOT NULL, 
	CONSTRAINT pk_statistical_profiles PRIMARY KEY (profile_id), 
	CONSTRAINT uq_statistical_profiles_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_statistical_profiles_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_statistical_profiles_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_statistical_profiles_column ON statistical_profiles (column_id, profiled_at DESC);

CREATE INDEX ix_statistical_profiles_session_id ON statistical_profiles (session_id);

CREATE TABLE statistical_quality_metrics (
	metric_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	benford_compliant INTEGER, 
	has_outliers INTEGER, 
	iqr_outlier_ratio FLOAT, 
	zscore_outlier_ratio FLOAT, 
	quality_data JSON NOT NULL, 
	CONSTRAINT pk_statistical_quality_metrics PRIMARY KEY (metric_id), 
	CONSTRAINT uq_statistical_quality_metrics_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_statistical_quality_metrics_session_id_investigation_dfcf FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_statistical_quality_metrics_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_statistical_quality_column ON statistical_quality_metrics (column_id, computed_at DESC);

CREATE INDEX ix_statistical_quality_metrics_session_id ON statistical_quality_metrics (session_id);

CREATE TABLE temporal_column_profiles (
	profile_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	profiled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	min_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	max_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	detected_granularity VARCHAR NOT NULL, 
	completeness_ratio FLOAT, 
	has_seasonality BOOLEAN, 
	has_trend BOOLEAN, 
	is_stale BOOLEAN, 
	profile_data JSON NOT NULL, 
	CONSTRAINT pk_temporal_column_profiles PRIMARY KEY (profile_id), 
	CONSTRAINT uq_temporal_column_profiles_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_temporal_column_profiles_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_temporal_column_profiles_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_temporal_profiles_column ON temporal_column_profiles (column_id);

CREATE INDEX ix_temporal_column_profiles_session_id ON temporal_column_profiles (session_id);

CREATE TABLE type_candidates (
	candidate_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	data_type VARCHAR NOT NULL, 
	confidence FLOAT NOT NULL, 
	parse_success_rate FLOAT, 
	failed_examples JSON, 
	detected_pattern VARCHAR, 
	pattern_match_rate FLOAT, 
	detected_unit VARCHAR, 
	unit_confidence FLOAT, 
	quarantine_count INTEGER, 
	quarantine_rate FLOAT, 
	CONSTRAINT pk_type_candidates PRIMARY KEY (candidate_id), 
	CONSTRAINT fk_type_candidates_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_type_candidates_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_type_candidates_column ON type_candidates (column_id);

CREATE INDEX ix_type_candidates_session_id ON type_candidates (session_id);

CREATE TABLE type_decisions (
	decision_id VARCHAR NOT NULL, 
	session_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR, 
	decided_type VARCHAR NOT NULL, 
	decision_source VARCHAR NOT NULL, 
	decided_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	decided_by VARCHAR, 
	previous_type VARCHAR, 
	decision_reason VARCHAR, 
	CONSTRAINT pk_type_decisions PRIMARY KEY (decision_id), 
	CONSTRAINT uq_column_type_decision UNIQUE (column_id, run_id), 
	CONSTRAINT fk_type_decisions_session_id_investigation_sessions FOREIGN KEY(session_id) REFERENCES investigation_sessions (session_id), 
	CONSTRAINT fk_type_decisions_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id) ON DELETE CASCADE
);

CREATE INDEX idx_type_decisions_column ON type_decisions (column_id);

CREATE INDEX ix_type_decisions_session_id ON type_decisions (session_id);
