-- GENERATED by `uv run python -m dataraum.storage.dump_ddl` — do not edit.
-- Source of truth: the SQLAlchemy models (storage.base.load_all_models).
-- Schema-less on purpose: apply with search_path set to the target ws_<id>.

CREATE TABLE config_overlay (
	overlay_id VARCHAR NOT NULL, 
	type VARCHAR NOT NULL, 
	payload JSON NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	superseded_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT pk_config_overlay PRIMARY KEY (overlay_id)
);

CREATE INDEX idx_config_overlay_active ON config_overlay (superseded_at, type);

CREATE TABLE detected_business_cycles (
	cycle_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	cycle_name VARCHAR NOT NULL, 
	cycle_type VARCHAR NOT NULL, 
	canonical_type VARCHAR NOT NULL, 
	is_known_type BOOLEAN NOT NULL, 
	description TEXT, 
	business_value VARCHAR NOT NULL, 
	confidence FLOAT NOT NULL, 
	tables_involved JSON NOT NULL, 
	stages JSON NOT NULL, 
	entity_flows JSON NOT NULL, 
	status_table VARCHAR, 
	status_column VARCHAR, 
	completion_value VARCHAR, 
	total_records INTEGER, 
	completed_cycles INTEGER, 
	completion_rate FLOAT, 
	evidence JSON NOT NULL, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_detected_business_cycles PRIMARY KEY (cycle_id), 
	CONSTRAINT uq_detected_cycle_run UNIQUE (canonical_type, run_id)
);

CREATE TABLE lifecycle_artifacts (
	artifact_id VARCHAR NOT NULL, 
	artifact_type VARCHAR NOT NULL, 
	artifact_key VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	state VARCHAR NOT NULL, 
	state_reason TEXT, 
	stage VARCHAR NOT NULL, 
	strictness FLOAT, 
	grounded_against JSON, 
	teaches JSON, 
	graph_definition JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	state_changed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_lifecycle_artifacts PRIMARY KEY (artifact_id), 
	CONSTRAINT uq_lifecycle_artifact_identity UNIQUE (artifact_type, artifact_key, run_id)
);

CREATE TABLE metadata_snapshot_head (
	head_id VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	stage VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	promoted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_metadata_snapshot_head PRIMARY KEY (head_id), 
	CONSTRAINT uq_snapshot_head_target_stage UNIQUE (target, stage)
);

CREATE TABLE sources (
	source_id VARCHAR NOT NULL, 
	name VARCHAR NOT NULL, 
	source_type VARCHAR NOT NULL, 
	connection_config JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	status VARCHAR, 
	stage VARCHAR, 
	backend VARCHAR, 
	discovered_schema JSON, 
	archived_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT pk_sources PRIMARY KEY (source_id), 
	CONSTRAINT uq_sources_name UNIQUE (name)
);

CREATE TABLE sql_snippets (
	snippet_id VARCHAR NOT NULL, 
	workspace_id VARCHAR NOT NULL, 
	snippet_type VARCHAR NOT NULL, 
	standard_field VARCHAR, 
	statement VARCHAR, 
	aggregation VARCHAR, 
	schema_mapping_id VARCHAR NOT NULL, 
	parameter_value VARCHAR, 
	normalized_expression VARCHAR, 
	input_fields JSON, 
	sql TEXT NOT NULL, 
	description TEXT NOT NULL, 
	column_mappings JSON NOT NULL, 
	source VARCHAR NOT NULL, 
	llm_model VARCHAR, 
	provenance JSON, 
	execution_count INTEGER NOT NULL, 
	failure_count INTEGER NOT NULL, 
	last_used_at TIMESTAMP WITHOUT TIME ZONE, 
	column_hash VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_sql_snippets PRIMARY KEY (snippet_id), 
	CONSTRAINT uq_snippet_semantic_key UNIQUE (snippet_type, standard_field, statement, aggregation, schema_mapping_id, parameter_value)
);

CREATE INDEX ix_sql_snippets_normalized_expression ON sql_snippets (normalized_expression);

CREATE INDEX ix_sql_snippets_schema_mapping_id ON sql_snippets (schema_mapping_id);

CREATE INDEX ix_sql_snippets_snippet_type ON sql_snippets (snippet_type);

CREATE INDEX ix_sql_snippets_standard_field ON sql_snippets (standard_field);

CREATE INDEX ix_sql_snippets_workspace_id ON sql_snippets (workspace_id);

CREATE TABLE validation_results (
	result_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	validation_id VARCHAR NOT NULL, 
	table_ids JSON NOT NULL, 
	columns_used JSON NOT NULL, 
	sql_used TEXT, 
	executed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_validation_results PRIMARY KEY (result_id), 
	CONSTRAINT uq_validation_result_run UNIQUE (validation_id, run_id)
);

CREATE INDEX ix_validation_results_validation_id ON validation_results (validation_id);

CREATE TABLE fix_ledger (
	fix_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	action_name VARCHAR NOT NULL, 
	table_name VARCHAR NOT NULL, 
	column_name VARCHAR, 
	user_input VARCHAR NOT NULL, 
	interpretation VARCHAR NOT NULL, 
	status VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	superseded_at TIMESTAMP WITHOUT TIME ZONE, 
	superseded_by VARCHAR, 
	CONSTRAINT pk_fix_ledger PRIMARY KEY (fix_id), 
	CONSTRAINT fk_fix_ledger_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id), 
	CONSTRAINT fk_fix_ledger_superseded_by_fix_ledger FOREIGN KEY(superseded_by) REFERENCES fix_ledger (fix_id)
);

CREATE INDEX idx_fix_ledger_scope ON fix_ledger (source_id, action_name, table_name, column_name);

CREATE INDEX idx_fix_ledger_source ON fix_ledger (source_id);

CREATE TABLE snippet_usage (
	usage_id VARCHAR NOT NULL, 
	workspace_id VARCHAR NOT NULL, 
	execution_id VARCHAR NOT NULL, 
	execution_type VARCHAR NOT NULL, 
	snippet_id VARCHAR, 
	usage_type VARCHAR NOT NULL, 
	match_confidence FLOAT NOT NULL, 
	sql_match_ratio FLOAT NOT NULL, 
	step_id VARCHAR, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_snippet_usage PRIMARY KEY (usage_id), 
	CONSTRAINT fk_snippet_usage_snippet_id_sql_snippets FOREIGN KEY(snippet_id) REFERENCES sql_snippets (snippet_id) ON DELETE CASCADE
);

CREATE INDEX ix_snippet_usage_execution_id ON snippet_usage (execution_id);

CREATE INDEX ix_snippet_usage_snippet_id ON snippet_usage (snippet_id);

CREATE INDEX ix_snippet_usage_workspace_id ON snippet_usage (workspace_id);

CREATE TABLE tables (
	table_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	table_name VARCHAR NOT NULL, 
	layer VARCHAR NOT NULL, 
	duckdb_path VARCHAR, 
	row_count INTEGER, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	last_profiled_at TIMESTAMP WITHOUT TIME ZONE, 
	CONSTRAINT pk_tables PRIMARY KEY (table_id), 
	CONSTRAINT uq_table_name_layer UNIQUE (table_name, layer), 
	CONSTRAINT fk_tables_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id)
);

CREATE INDEX idx_tables_source ON tables (source_id);

CREATE TABLE column_eligibility (
	eligibility_id VARCHAR(36) NOT NULL, 
	column_id VARCHAR(36) NOT NULL, 
	table_id VARCHAR NOT NULL, 
	source_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	column_name VARCHAR NOT NULL, 
	table_name VARCHAR NOT NULL, 
	resolved_type VARCHAR, 
	status VARCHAR(20) NOT NULL, 
	triggered_rule VARCHAR(50), 
	reason TEXT, 
	metrics_snapshot JSON NOT NULL, 
	config_version VARCHAR(20) NOT NULL, 
	evaluated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_column_eligibility PRIMARY KEY (eligibility_id), 
	CONSTRAINT uq_column_eligibility_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_column_eligibility_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_column_eligibility_source_id_sources FOREIGN KEY(source_id) REFERENCES sources (source_id)
);

CREATE INDEX idx_eligibility_column ON column_eligibility (column_id);

CREATE INDEX idx_eligibility_source ON column_eligibility (source_id);

CREATE INDEX idx_eligibility_status ON column_eligibility (status);

CREATE INDEX idx_eligibility_table ON column_eligibility (table_id);

CREATE TABLE columns (
	column_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	column_name VARCHAR NOT NULL, 
	original_name VARCHAR, 
	column_position INTEGER NOT NULL, 
	raw_type VARCHAR, 
	resolved_type VARCHAR, 
	CONSTRAINT pk_columns PRIMARY KEY (column_id), 
	CONSTRAINT uq_table_column UNIQUE (table_id, column_name), 
	CONSTRAINT fk_columns_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id) ON DELETE CASCADE
);

CREATE INDEX idx_columns_table ON columns (table_id);

CREATE TABLE dimension_hierarchies (
	hierarchy_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	kind VARCHAR NOT NULL, 
	members JSON NOT NULL, 
	canonical_label VARCHAR NOT NULL, 
	signature VARCHAR NOT NULL, 
	score FLOAT NOT NULL, 
	detection_source VARCHAR NOT NULL, 
	needs_confirmation BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_dimension_hierarchies PRIMARY KEY (hierarchy_id), 
	CONSTRAINT uq_dimension_hierarchy_signature_run UNIQUE (signature, run_id), 
	CONSTRAINT fk_dimension_hierarchies_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id)
);

CREATE INDEX idx_dimension_hierarchies_run ON dimension_hierarchies (run_id);

CREATE INDEX idx_dimension_hierarchies_table ON dimension_hierarchies (table_id);

CREATE TABLE enriched_views (
	view_id VARCHAR NOT NULL, 
	fact_table_id VARCHAR NOT NULL, 
	view_table_id VARCHAR, 
	view_name VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	relationship_ids JSON, 
	considered_relationship_pairs JSON, 
	exposed_dimension_joins JSON, 
	dimension_table_ids JSON, 
	dimension_columns JSON, 
	is_grain_verified BOOLEAN NOT NULL, 
	evidence JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_enriched_views PRIMARY KEY (view_id), 
	CONSTRAINT uq_enriched_view_fact_table UNIQUE (fact_table_id), 
	CONSTRAINT fk_enriched_views_fact_table_id_tables FOREIGN KEY(fact_table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_enriched_views_view_table_id_tables FOREIGN KEY(view_table_id) REFERENCES tables (table_id)
);

CREATE INDEX ix_enriched_views_run_id ON enriched_views (run_id);

CREATE TABLE materialization_recipes (
	recipe_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	layer VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	target_fqn VARCHAR NOT NULL, 
	ddl VARCHAR NOT NULL, 
	depends_on JSON, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_materialization_recipes PRIMARY KEY (recipe_id), 
	CONSTRAINT uq_materialization_recipe_table_layer_run UNIQUE (table_id, layer, run_id), 
	CONSTRAINT fk_materialization_recipes_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id)
);

CREATE INDEX idx_materialization_recipes_table ON materialization_recipes (table_id);

CREATE TABLE run_tables (
	run_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	CONSTRAINT pk_run_tables PRIMARY KEY (run_id, table_id), 
	CONSTRAINT fk_run_tables_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id)
);

CREATE INDEX idx_run_tables_table ON run_tables (table_id);

CREATE TABLE table_entities (
	entity_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	detected_entity_type VARCHAR NOT NULL, 
	description TEXT, 
	confidence FLOAT, 
	evidence JSON, 
	grain_columns JSON, 
	is_fact_table BOOLEAN, 
	is_dimension_table BOOLEAN, 
	time_columns JSON, 
	identity_columns JSON, 
	detection_source VARCHAR, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_table_entities PRIMARY KEY (entity_id), 
	CONSTRAINT uq_table_entity_table_run UNIQUE (table_id, run_id), 
	CONSTRAINT fk_table_entities_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id)
);

CREATE TABLE claim_witnesses (
	claim_witness_id VARCHAR NOT NULL, 
	table_id VARCHAR, 
	column_id VARCHAR, 
	run_id VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	claim_field VARCHAR NOT NULL, 
	witness_id VARCHAR NOT NULL, 
	distribution JSONB, 
	reliability FLOAT NOT NULL, 
	detector_id VARCHAR NOT NULL, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_claim_witnesses PRIMARY KEY (claim_witness_id), 
	CONSTRAINT uq_claim_witness_target_field_witness_run UNIQUE (target, claim_field, witness_id, run_id), 
	CONSTRAINT fk_claim_witnesses_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_claim_witnesses_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_claim_witness_column ON claim_witnesses (column_id);

CREATE INDEX idx_claim_witness_table ON claim_witnesses (table_id);

CREATE INDEX idx_claim_witness_target ON claim_witnesses (target);

CREATE TABLE column_concepts (
	concept_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	business_concept VARCHAR, 
	temporal_behavior VARCHAR, 
	temporal_behavior_contested BOOLEAN, 
	unit_source_column VARCHAR, 
	derived_formula_hypothesis VARCHAR, 
	derived_formula_confidence FLOAT, 
	annotation_source VARCHAR, 
	annotated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	annotated_by VARCHAR, 
	confidence FLOAT, 
	CONSTRAINT pk_column_concepts PRIMARY KEY (concept_id), 
	CONSTRAINT uq_column_concept UNIQUE (column_id, run_id), 
	CONSTRAINT fk_column_concepts_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE TABLE derived_columns (
	derived_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	derived_column_id VARCHAR NOT NULL, 
	source_column_ids JSON NOT NULL, 
	derivation_type VARCHAR NOT NULL, 
	formula VARCHAR NOT NULL, 
	match_rate FLOAT NOT NULL, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	total_rows INTEGER NOT NULL, 
	matching_rows INTEGER NOT NULL, 
	mismatch_examples JSON, 
	CONSTRAINT pk_derived_columns PRIMARY KEY (derived_id), 
	CONSTRAINT fk_derived_columns_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_derived_columns_derived_column_id_columns FOREIGN KEY(derived_column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_derived_column ON derived_columns (derived_column_id);

CREATE INDEX idx_derived_table ON derived_columns (table_id);

CREATE INDEX ix_derived_columns_run_id ON derived_columns (run_id);

CREATE TABLE driver_rankings (
	ranking_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	measure_table_id VARCHAR NOT NULL, 
	measure_column_id VARCHAR NOT NULL, 
	measure_label VARCHAR NOT NULL, 
	target_type VARCHAR NOT NULL, 
	grain VARCHAR NOT NULL, 
	entity VARCHAR, 
	n_rows INTEGER NOT NULL, 
	ranked_dimensions JSON NOT NULL, 
	driver_paths JSON NOT NULL, 
	interesting_slices JSON NOT NULL, 
	secondary_dimensions JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_driver_rankings PRIMARY KEY (ranking_id), 
	CONSTRAINT uq_driver_rankings_column_run UNIQUE (measure_column_id, run_id), 
	CONSTRAINT fk_driver_rankings_measure_table_id_tables FOREIGN KEY(measure_table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_driver_rankings_measure_column_id_columns FOREIGN KEY(measure_column_id) REFERENCES columns (column_id)
);

CREATE INDEX ix_driver_rankings_measure_column_id ON driver_rankings (measure_column_id);

CREATE INDEX ix_driver_rankings_run_id ON driver_rankings (run_id);

CREATE TABLE entropy_objects (
	object_id VARCHAR NOT NULL, 
	layer VARCHAR NOT NULL, 
	dimension VARCHAR NOT NULL, 
	sub_dimension VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	table_id VARCHAR, 
	column_id VARCHAR, 
	run_id VARCHAR NOT NULL, 
	score FLOAT NOT NULL, 
	evidence JSONB, 
	detector_id VARCHAR NOT NULL, 
	source_analysis_ids JSONB, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_entropy_objects PRIMARY KEY (object_id), 
	CONSTRAINT fk_entropy_objects_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_entropy_objects_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_entropy_column ON entropy_objects (column_id);

CREATE INDEX idx_entropy_layer_dimension ON entropy_objects (layer, dimension);

CREATE INDEX idx_entropy_score ON entropy_objects (score);

CREATE INDEX idx_entropy_table ON entropy_objects (table_id);

CREATE INDEX idx_entropy_target ON entropy_objects (target);

CREATE TABLE entropy_readiness (
	readiness_id VARCHAR NOT NULL, 
	target VARCHAR NOT NULL, 
	table_id VARCHAR, 
	column_id VARCHAR, 
	run_id VARCHAR NOT NULL, 
	band VARCHAR NOT NULL, 
	worst_intent_risk FLOAT NOT NULL, 
	intents JSONB, 
	top_drivers JSONB, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_entropy_readiness PRIMARY KEY (readiness_id), 
	CONSTRAINT fk_entropy_readiness_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_entropy_readiness_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_readiness_column ON entropy_readiness (column_id);

CREATE INDEX idx_readiness_table ON entropy_readiness (table_id);

CREATE INDEX idx_readiness_target ON entropy_readiness (target);

CREATE TABLE measure_aggregation_lineage (
	lineage_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	measure_table_id VARCHAR NOT NULL, 
	measure_column_id VARCHAR NOT NULL, 
	event_table_id VARCHAR NOT NULL, 
	slice_dimension VARCHAR NOT NULL, 
	convention_sql TEXT NOT NULL, 
	period_grain VARCHAR NOT NULL, 
	pattern VARCHAR NOT NULL, 
	match_rate FLOAT NOT NULL, 
	r_flow_median FLOAT NOT NULL, 
	r_stock_median FLOAT NOT NULL, 
	n_entities INTEGER NOT NULL, 
	n_entities_fired INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	CONSTRAINT pk_measure_aggregation_lineage PRIMARY KEY (lineage_id), 
	CONSTRAINT uq_measure_lineage_column_run UNIQUE (measure_column_id, run_id), 
	CONSTRAINT fk_measure_aggregation_lineage_measure_table_id_tables FOREIGN KEY(measure_table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_measure_aggregation_lineage_measure_column_id_columns FOREIGN KEY(measure_column_id) REFERENCES columns (column_id), 
	CONSTRAINT fk_measure_aggregation_lineage_event_table_id_tables FOREIGN KEY(event_table_id) REFERENCES tables (table_id)
);

CREATE INDEX ix_measure_aggregation_lineage_measure_column_id ON measure_aggregation_lineage (measure_column_id);

CREATE INDEX ix_measure_aggregation_lineage_run_id ON measure_aggregation_lineage (run_id);

CREATE TABLE relationships (
	relationship_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	from_table_id VARCHAR NOT NULL, 
	from_column_id VARCHAR NOT NULL, 
	to_table_id VARCHAR NOT NULL, 
	to_column_id VARCHAR NOT NULL, 
	relationship_type VARCHAR NOT NULL, 
	cardinality VARCHAR, 
	confidence FLOAT NOT NULL, 
	detection_method VARCHAR, 
	evidence JSON, 
	is_confirmed BOOLEAN NOT NULL, 
	confirmed_at TIMESTAMP WITHOUT TIME ZONE, 
	confirmed_by VARCHAR, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_relationships PRIMARY KEY (relationship_id), 
	CONSTRAINT uq_relationship_columns_method UNIQUE (run_id, from_column_id, to_column_id, detection_method), 
	CONSTRAINT fk_relationships_from_table_id_tables FOREIGN KEY(from_table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_relationships_from_column_id_columns FOREIGN KEY(from_column_id) REFERENCES columns (column_id), 
	CONSTRAINT fk_relationships_to_table_id_tables FOREIGN KEY(to_table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_relationships_to_column_id_columns FOREIGN KEY(to_column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_relationships_from ON relationships (from_table_id);

CREATE INDEX idx_relationships_from_column ON relationships (from_column_id);

CREATE INDEX idx_relationships_from_table_column ON relationships (from_table_id, from_column_id);

CREATE INDEX idx_relationships_to ON relationships (to_table_id);

CREATE INDEX idx_relationships_to_column ON relationships (to_column_id);

CREATE INDEX idx_relationships_to_table_column ON relationships (to_table_id, to_column_id);

CREATE INDEX ix_relationships_run_id ON relationships (run_id);

CREATE TABLE semantic_annotations (
	annotation_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	semantic_role VARCHAR, 
	entity_type VARCHAR, 
	business_name VARCHAR, 
	business_description TEXT, 
	temporal_behavior_claim VARCHAR, 
	temporal_behavior_claim_confidence FLOAT, 
	null_tokens JSON, 
	annotation_source VARCHAR, 
	annotated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	annotated_by VARCHAR, 
	confidence FLOAT, 
	CONSTRAINT pk_semantic_annotations PRIMARY KEY (annotation_id), 
	CONSTRAINT uq_column_semantic_annotation UNIQUE (column_id, run_id), 
	CONSTRAINT fk_semantic_annotations_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE TABLE slice_definitions (
	slice_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	table_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	column_name VARCHAR, 
	slice_priority INTEGER NOT NULL, 
	slice_type VARCHAR NOT NULL, 
	distinct_values JSON, 
	value_count INTEGER, 
	reasoning TEXT, 
	business_context TEXT, 
	confidence FLOAT, 
	detection_source VARCHAR NOT NULL, 
	created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	CONSTRAINT pk_slice_definitions PRIMARY KEY (slice_id), 
	CONSTRAINT uq_slice_def_table_column_run UNIQUE (table_id, column_name, run_id), 
	CONSTRAINT fk_slice_definitions_table_id_tables FOREIGN KEY(table_id) REFERENCES tables (table_id), 
	CONSTRAINT fk_slice_definitions_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_slice_definitions_column ON slice_definitions (column_id);

CREATE INDEX idx_slice_definitions_table ON slice_definitions (table_id);

CREATE TABLE statistical_profiles (
	profile_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	profiled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	layer VARCHAR NOT NULL, 
	total_count INTEGER NOT NULL, 
	null_count INTEGER NOT NULL, 
	distinct_count INTEGER, 
	null_ratio FLOAT, 
	cardinality_ratio FLOAT, 
	is_unique INTEGER, 
	is_numeric INTEGER, 
	profile_data JSON NOT NULL, 
	CONSTRAINT pk_statistical_profiles PRIMARY KEY (profile_id), 
	CONSTRAINT uq_statistical_profiles_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_statistical_profiles_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_statistical_profiles_column ON statistical_profiles (column_id, profiled_at DESC);

CREATE INDEX ix_statistical_profiles_run_id ON statistical_profiles (run_id);

CREATE TABLE statistical_quality_metrics (
	metric_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	computed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	benford_compliant INTEGER, 
	has_outliers INTEGER, 
	iqr_outlier_ratio FLOAT, 
	zscore_outlier_ratio FLOAT, 
	quality_data JSON NOT NULL, 
	CONSTRAINT pk_statistical_quality_metrics PRIMARY KEY (metric_id), 
	CONSTRAINT uq_statistical_quality_metrics_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_statistical_quality_metrics_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_statistical_quality_column ON statistical_quality_metrics (column_id, computed_at DESC);

CREATE INDEX ix_statistical_quality_metrics_run_id ON statistical_quality_metrics (run_id);

CREATE TABLE temporal_column_profiles (
	profile_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	profiled_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	min_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	max_timestamp TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	detected_granularity VARCHAR NOT NULL, 
	completeness_ratio FLOAT, 
	is_stale BOOLEAN, 
	profile_data JSON NOT NULL, 
	CONSTRAINT pk_temporal_column_profiles PRIMARY KEY (profile_id), 
	CONSTRAINT uq_temporal_column_profiles_column_run UNIQUE (column_id, run_id), 
	CONSTRAINT fk_temporal_column_profiles_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_temporal_profiles_column ON temporal_column_profiles (column_id);

CREATE TABLE type_candidates (
	candidate_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	detected_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	data_type VARCHAR NOT NULL, 
	confidence FLOAT NOT NULL, 
	parse_success_rate FLOAT, 
	failed_examples JSON, 
	detected_pattern VARCHAR DEFAULT '' NOT NULL, 
	pattern_match_rate FLOAT, 
	detected_unit VARCHAR, 
	unit_confidence FLOAT, 
	quarantine_count INTEGER, 
	quarantine_rate FLOAT, 
	CONSTRAINT pk_type_candidates PRIMARY KEY (candidate_id), 
	CONSTRAINT uq_type_candidate_column_type_pattern_run UNIQUE (column_id, data_type, detected_pattern, run_id), 
	CONSTRAINT fk_type_candidates_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_type_candidates_column ON type_candidates (column_id);

CREATE TABLE type_decisions (
	decision_id VARCHAR NOT NULL, 
	column_id VARCHAR NOT NULL, 
	run_id VARCHAR NOT NULL, 
	decided_type VARCHAR NOT NULL, 
	decision_source VARCHAR NOT NULL, 
	decided_at TIMESTAMP WITHOUT TIME ZONE NOT NULL, 
	decided_by VARCHAR, 
	previous_type VARCHAR, 
	decision_reason VARCHAR, 
	CONSTRAINT pk_type_decisions PRIMARY KEY (decision_id), 
	CONSTRAINT uq_column_type_decision UNIQUE (column_id, run_id), 
	CONSTRAINT fk_type_decisions_column_id_columns FOREIGN KEY(column_id) REFERENCES columns (column_id)
);

CREATE INDEX idx_type_decisions_column ON type_decisions (column_id);
