"""Vertical Agent — LLM-powered ontology generation.

Creates ontology definitions for new verticals from a target taxonomy
(e.g. DATEV accounts) and source column names. Follows the same pattern
as SemanticAgent: inherits LLMFeature, uses PromptRenderer, returns Result.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

from pydantic import BaseModel, Field

from dataraum.analysis.semantic.ontology import OntologyDefinition, OntologyLoader
from dataraum.core.models.base import Result
from dataraum.llm.features._base import LLMFeature
from dataraum.llm.providers.base import ConversationRequest, Message, ToolDefinition

if TYPE_CHECKING:
    from dataraum.llm.config import LLMConfig
    from dataraum.llm.prompts import PromptRenderer
    from dataraum.llm.providers.base import LLMProvider


class GeneratedConcept(BaseModel):
    """A single ontology concept generated by the LLM."""

    name: str
    description: str
    indicators: list[str] = Field(default_factory=list)
    exclude_patterns: list[str] = Field(default_factory=list)
    temporal_behavior: str
    typical_role: str
    unit_from_concept: str | None = None
    is_unit_dimension: bool = False


class VerticalCreationOutput(BaseModel):
    """Structured output from the vertical creation LLM call."""

    name: str
    description: str
    concepts: list[GeneratedConcept]


class VerticalAgent(LLMFeature):
    """LLM-powered ontology generation agent.

    Given a domain description, source column names, and a target taxonomy
    (e.g. DATEV accounts), generates an OntologyDefinition with one concept
    per taxonomy entry, with indicators derived from source column names.
    """

    def __init__(
        self,
        config: LLMConfig,
        provider: LLMProvider,
        prompt_renderer: PromptRenderer,
        verticals_dir: Path | None = None,
    ) -> None:
        """Initialize vertical agent.

        Args:
            config: LLM configuration
            provider: LLM provider instance
            prompt_renderer: Prompt template renderer
            verticals_dir: Root verticals directory. If None, uses config/verticals/
        """
        super().__init__(config, provider, prompt_renderer)
        self._ontology_loader = OntologyLoader(verticals_dir)

    def generate(
        self,
        vertical_name: str,
        domain_description: str,
        source_columns: list[str],
        target_taxonomy: list[dict[str, Any]],
        base_vertical: str | None = None,
    ) -> Result[OntologyDefinition]:
        """Generate an ontology definition for a new vertical.

        Args:
            vertical_name: Name for the new vertical (e.g. 'shopify_datev')
            domain_description: Human description of the domain and transformation goal
            source_columns: Column names from the source data
            target_taxonomy: Target classification entries, each dict with at minimum
                'name' and 'type'. Each entry becomes one ontology concept.
            base_vertical: Optional existing vertical to inherit concepts from

        Returns:
            Result containing OntologyDefinition or error message
        """
        feature_config = self.config.features.vertical_creation
        if feature_config is not None and not feature_config.enabled:
            return Result.fail("Vertical creation is disabled in config")

        # Build base concepts section if inheriting from an existing vertical
        base_concepts_section = ""
        if base_vertical:
            base_ontology = self._ontology_loader.load(base_vertical)
            if base_ontology is None:
                available = self._ontology_loader.list_verticals()
                return Result.fail(
                    f"Base vertical '{base_vertical}' not found. Available: {available}"
                )
            base_concepts_section = (
                f"<base_vertical name='{base_vertical}'>\n"
                f"You may reference or extend these existing concepts:\n"
                + self._ontology_loader.format_concepts_for_prompt(base_ontology)
                + "\n</base_vertical>"
            )

        context = {
            "vertical_name": vertical_name,
            "domain_description": domain_description,
            "source_columns": "\n".join(f"  - {c}" for c in source_columns) or "  (none provided)",
            "target_taxonomy_json": json.dumps(target_taxonomy, indent=2, ensure_ascii=False),
            "base_concepts_section": base_concepts_section,
        }

        try:
            system_prompt, user_prompt, temperature = self.renderer.render_split(
                "vertical_creation", context
            )
        except Exception as e:
            return Result.fail(f"Failed to render prompt: {e}")

        tool = ToolDefinition(
            name="create_ontology",
            description="Provide the generated ontology definition for the new vertical.",
            input_schema=VerticalCreationOutput.model_json_schema(),
        )

        model_tier = "balanced"
        if feature_config is not None:
            model_tier = feature_config.model_tier

        model = self.provider.get_model_for_tier(model_tier)
        request = ConversationRequest(
            messages=[Message(role="user", content=user_prompt)],
            system=system_prompt,
            tools=[tool],
            tool_choice={"type": "tool", "name": "create_ontology"},
            max_tokens=self.config.limits.max_output_tokens_per_request,
            temperature=temperature,
            model=model,
        )

        response_result = self.provider.converse(request)
        if not response_result.success or not response_result.value:
            return Result.fail(response_result.error or "LLM call failed")

        response = response_result.value

        if not response.tool_calls:
            return Result.fail(
                f"LLM did not use the create_ontology tool. "
                f"Response: {(response.content or '')[:500]}"
            )

        tool_call = response.tool_calls[0]
        if tool_call.name != "create_ontology":
            return Result.fail(f"Unexpected tool call: {tool_call.name}")

        try:
            output = VerticalCreationOutput.model_validate(tool_call.input)
        except Exception as e:
            return Result.fail(f"Failed to parse ontology output: {e}")

        # Convert to OntologyDefinition (reuses existing Pydantic models)
        from dataraum.analysis.semantic.ontology import OntologyConcept

        concepts = [
            OntologyConcept(
                name=c.name,
                description=c.description,
                indicators=c.indicators,
                exclude_patterns=c.exclude_patterns,
                temporal_behavior=c.temporal_behavior,
                typical_role=c.typical_role,
                unit_from_concept=c.unit_from_concept,
                is_unit_dimension=c.is_unit_dimension,
            )
            for c in output.concepts
        ]

        ontology = OntologyDefinition(
            name=output.name,
            version="1.0.0",
            description=output.description,
            concepts=concepts,
        )

        return Result.ok(ontology)
