/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiRunSqlRouteImport } from './routes/api/run-sql'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAddSourceProgressRouteImport } from './routes/api/add-source-progress'
import { Route as ApiAddSourceRouteImport } from './routes/api/add-source'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appWorkspaceWsIdRouteRouteImport } from './routes/(app)/workspace/$wsId/route'
import { Route as appWorkspaceWsIdWorkflowsRouteImport } from './routes/(app)/workspace/$wsId/workflows'
import { Route as appWorkspaceWsIdMetadataRouteImport } from './routes/(app)/workspace/$wsId/metadata'
import { Route as appWorkspaceWsIdLibraryRouteImport } from './routes/(app)/workspace/$wsId/library'
import { Route as appWorkspaceWsIdGovernanceRouteImport } from './routes/(app)/workspace/$wsId/governance'
import { Route as appWorkspaceWsIdCockpitRouteImport } from './routes/(app)/workspace/$wsId/cockpit'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunSqlRoute = ApiRunSqlRouteImport.update({
  id: '/api/run-sql',
  path: '/api/run-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddSourceProgressRoute = ApiAddSourceProgressRouteImport.update({
  id: '/api/add-source-progress',
  path: '/api/add-source-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddSourceRoute = ApiAddSourceRouteImport.update({
  id: '/api/add-source',
  path: '/api/add-source',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appWorkspaceWsIdRouteRoute = appWorkspaceWsIdRouteRouteImport.update({
  id: '/workspace/$wsId',
  path: '/workspace/$wsId',
  getParentRoute: () => appRouteRoute,
} as any)
const appWorkspaceWsIdWorkflowsRoute =
  appWorkspaceWsIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdMetadataRoute =
  appWorkspaceWsIdMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdLibraryRoute = appWorkspaceWsIdLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => appWorkspaceWsIdRouteRoute,
} as any)
const appWorkspaceWsIdGovernanceRoute =
  appWorkspaceWsIdGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdCockpitRoute = appWorkspaceWsIdCockpitRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => appWorkspaceWsIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof appSettingsRoute
  '/api/add-source': typeof ApiAddSourceRoute
  '/api/add-source-progress': typeof ApiAddSourceProgressRoute
  '/api/chat': typeof ApiChatRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/upload': typeof ApiUploadRoute
  '/workspace/$wsId': typeof appWorkspaceWsIdRouteRouteWithChildren
  '/workspace/$wsId/cockpit': typeof appWorkspaceWsIdCockpitRoute
  '/workspace/$wsId/governance': typeof appWorkspaceWsIdGovernanceRoute
  '/workspace/$wsId/library': typeof appWorkspaceWsIdLibraryRoute
  '/workspace/$wsId/metadata': typeof appWorkspaceWsIdMetadataRoute
  '/workspace/$wsId/workflows': typeof appWorkspaceWsIdWorkflowsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof appSettingsRoute
  '/api/add-source': typeof ApiAddSourceRoute
  '/api/add-source-progress': typeof ApiAddSourceProgressRoute
  '/api/chat': typeof ApiChatRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/upload': typeof ApiUploadRoute
  '/workspace/$wsId': typeof appWorkspaceWsIdRouteRouteWithChildren
  '/workspace/$wsId/cockpit': typeof appWorkspaceWsIdCockpitRoute
  '/workspace/$wsId/governance': typeof appWorkspaceWsIdGovernanceRoute
  '/workspace/$wsId/library': typeof appWorkspaceWsIdLibraryRoute
  '/workspace/$wsId/metadata': typeof appWorkspaceWsIdMetadataRoute
  '/workspace/$wsId/workflows': typeof appWorkspaceWsIdWorkflowsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/api/add-source': typeof ApiAddSourceRoute
  '/api/add-source-progress': typeof ApiAddSourceProgressRoute
  '/api/chat': typeof ApiChatRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/upload': typeof ApiUploadRoute
  '/(app)/workspace/$wsId': typeof appWorkspaceWsIdRouteRouteWithChildren
  '/(app)/workspace/$wsId/cockpit': typeof appWorkspaceWsIdCockpitRoute
  '/(app)/workspace/$wsId/governance': typeof appWorkspaceWsIdGovernanceRoute
  '/(app)/workspace/$wsId/library': typeof appWorkspaceWsIdLibraryRoute
  '/(app)/workspace/$wsId/metadata': typeof appWorkspaceWsIdMetadataRoute
  '/(app)/workspace/$wsId/workflows': typeof appWorkspaceWsIdWorkflowsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/add-source'
    | '/api/add-source-progress'
    | '/api/chat'
    | '/api/run-sql'
    | '/api/upload'
    | '/workspace/$wsId'
    | '/workspace/$wsId/cockpit'
    | '/workspace/$wsId/governance'
    | '/workspace/$wsId/library'
    | '/workspace/$wsId/metadata'
    | '/workspace/$wsId/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/add-source'
    | '/api/add-source-progress'
    | '/api/chat'
    | '/api/run-sql'
    | '/api/upload'
    | '/workspace/$wsId'
    | '/workspace/$wsId/cockpit'
    | '/workspace/$wsId/governance'
    | '/workspace/$wsId/library'
    | '/workspace/$wsId/metadata'
    | '/workspace/$wsId/workflows'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/settings'
    | '/api/add-source'
    | '/api/add-source-progress'
    | '/api/chat'
    | '/api/run-sql'
    | '/api/upload'
    | '/(app)/workspace/$wsId'
    | '/(app)/workspace/$wsId/cockpit'
    | '/(app)/workspace/$wsId/governance'
    | '/(app)/workspace/$wsId/library'
    | '/(app)/workspace/$wsId/metadata'
    | '/(app)/workspace/$wsId/workflows'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  ApiAddSourceRoute: typeof ApiAddSourceRoute
  ApiAddSourceProgressRoute: typeof ApiAddSourceProgressRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRunSqlRoute: typeof ApiRunSqlRoute
  ApiUploadRoute: typeof ApiUploadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-sql': {
      id: '/api/run-sql'
      path: '/api/run-sql'
      fullPath: '/api/run-sql'
      preLoaderRoute: typeof ApiRunSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-source-progress': {
      id: '/api/add-source-progress'
      path: '/api/add-source-progress'
      fullPath: '/api/add-source-progress'
      preLoaderRoute: typeof ApiAddSourceProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/add-source': {
      id: '/api/add-source'
      path: '/api/add-source'
      fullPath: '/api/add-source'
      preLoaderRoute: typeof ApiAddSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/workspace/$wsId': {
      id: '/(app)/workspace/$wsId'
      path: '/workspace/$wsId'
      fullPath: '/workspace/$wsId'
      preLoaderRoute: typeof appWorkspaceWsIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/workspace/$wsId/workflows': {
      id: '/(app)/workspace/$wsId/workflows'
      path: '/workflows'
      fullPath: '/workspace/$wsId/workflows'
      preLoaderRoute: typeof appWorkspaceWsIdWorkflowsRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/metadata': {
      id: '/(app)/workspace/$wsId/metadata'
      path: '/metadata'
      fullPath: '/workspace/$wsId/metadata'
      preLoaderRoute: typeof appWorkspaceWsIdMetadataRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/library': {
      id: '/(app)/workspace/$wsId/library'
      path: '/library'
      fullPath: '/workspace/$wsId/library'
      preLoaderRoute: typeof appWorkspaceWsIdLibraryRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/governance': {
      id: '/(app)/workspace/$wsId/governance'
      path: '/governance'
      fullPath: '/workspace/$wsId/governance'
      preLoaderRoute: typeof appWorkspaceWsIdGovernanceRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/cockpit': {
      id: '/(app)/workspace/$wsId/cockpit'
      path: '/cockpit'
      fullPath: '/workspace/$wsId/cockpit'
      preLoaderRoute: typeof appWorkspaceWsIdCockpitRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
  }
}

interface appWorkspaceWsIdRouteRouteChildren {
  appWorkspaceWsIdCockpitRoute: typeof appWorkspaceWsIdCockpitRoute
  appWorkspaceWsIdGovernanceRoute: typeof appWorkspaceWsIdGovernanceRoute
  appWorkspaceWsIdLibraryRoute: typeof appWorkspaceWsIdLibraryRoute
  appWorkspaceWsIdMetadataRoute: typeof appWorkspaceWsIdMetadataRoute
  appWorkspaceWsIdWorkflowsRoute: typeof appWorkspaceWsIdWorkflowsRoute
}

const appWorkspaceWsIdRouteRouteChildren: appWorkspaceWsIdRouteRouteChildren = {
  appWorkspaceWsIdCockpitRoute: appWorkspaceWsIdCockpitRoute,
  appWorkspaceWsIdGovernanceRoute: appWorkspaceWsIdGovernanceRoute,
  appWorkspaceWsIdLibraryRoute: appWorkspaceWsIdLibraryRoute,
  appWorkspaceWsIdMetadataRoute: appWorkspaceWsIdMetadataRoute,
  appWorkspaceWsIdWorkflowsRoute: appWorkspaceWsIdWorkflowsRoute,
}

const appWorkspaceWsIdRouteRouteWithChildren =
  appWorkspaceWsIdRouteRoute._addFileChildren(
    appWorkspaceWsIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRoute
  appWorkspaceWsIdRouteRoute: typeof appWorkspaceWsIdRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRoute,
  appWorkspaceWsIdRouteRoute: appWorkspaceWsIdRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  ApiAddSourceRoute: ApiAddSourceRoute,
  ApiAddSourceProgressRoute: ApiAddSourceProgressRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRunSqlRoute: ApiRunSqlRoute,
  ApiUploadRoute: ApiUploadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
