/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkflowProgressRouteImport } from './routes/api/workflow-progress'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiShippedMetricDagRouteImport } from './routes/api/shipped-metric-dag'
import { Route as ApiRunningRunsRouteImport } from './routes/api/running-runs'
import { Route as ApiRunSqlRouteImport } from './routes/api/run-sql'
import { Route as ApiProbeSqlRouteImport } from './routes/api/probe-sql'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAwaitingInputRouteImport } from './routes/api/awaiting-input'
import { Route as appWorkflowsRouteImport } from './routes/(app)/workflows'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appOperatingModelRouteImport } from './routes/(app)/operating-model'
import { Route as appMetadataRouteImport } from './routes/(app)/metadata'
import { Route as appLibraryRouteImport } from './routes/(app)/library'
import { Route as appGovernanceRouteImport } from './routes/(app)/governance'
import { Route as appCockpitRouteRouteImport } from './routes/(app)/cockpit/route'
import { Route as appReportsIndexRouteImport } from './routes/(app)/reports/index'
import { Route as appCockpitIndexRouteImport } from './routes/(app)/cockpit/index'
import { Route as ApiReportsMintRouteImport } from './routes/api/reports/mint'
import { Route as ApiDrillNodeRouteImport } from './routes/api/drill/node'
import { Route as ApiDrillComposeRouteImport } from './routes/api/drill/compose'
import { Route as ApiDrillAxesRouteImport } from './routes/api/drill/axes'
import { Route as ApiChartsAuthorRouteImport } from './routes/api/charts/author'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appReportsReportIdRouteImport } from './routes/(app)/reports/$reportId'
import { Route as appCockpitConversationIdRouteImport } from './routes/(app)/cockpit/$conversationId'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowProgressRoute = ApiWorkflowProgressRouteImport.update({
  id: '/api/workflow-progress',
  path: '/api/workflow-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippedMetricDagRoute = ApiShippedMetricDagRouteImport.update({
  id: '/api/shipped-metric-dag',
  path: '/api/shipped-metric-dag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunningRunsRoute = ApiRunningRunsRouteImport.update({
  id: '/api/running-runs',
  path: '/api/running-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunSqlRoute = ApiRunSqlRouteImport.update({
  id: '/api/run-sql',
  path: '/api/run-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbeSqlRoute = ApiProbeSqlRouteImport.update({
  id: '/api/probe-sql',
  path: '/api/probe-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwaitingInputRoute = ApiAwaitingInputRouteImport.update({
  id: '/api/awaiting-input',
  path: '/api/awaiting-input',
  getParentRoute: () => rootRouteImport,
} as any)
const appWorkflowsRoute = appWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appOperatingModelRoute = appOperatingModelRouteImport.update({
  id: '/operating-model',
  path: '/operating-model',
  getParentRoute: () => appRouteRoute,
} as any)
const appMetadataRoute = appMetadataRouteImport.update({
  id: '/metadata',
  path: '/metadata',
  getParentRoute: () => appRouteRoute,
} as any)
const appLibraryRoute = appLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => appRouteRoute,
} as any)
const appGovernanceRoute = appGovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => appRouteRoute,
} as any)
const appCockpitRouteRoute = appCockpitRouteRouteImport.update({
  id: '/cockpit',
  path: '/cockpit',
  getParentRoute: () => appRouteRoute,
} as any)
const appReportsIndexRoute = appReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => appRouteRoute,
} as any)
const appCockpitIndexRoute = appCockpitIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appCockpitRouteRoute,
} as any)
const ApiReportsMintRoute = ApiReportsMintRouteImport.update({
  id: '/api/reports/mint',
  path: '/api/reports/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillNodeRoute = ApiDrillNodeRouteImport.update({
  id: '/api/drill/node',
  path: '/api/drill/node',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillComposeRoute = ApiDrillComposeRouteImport.update({
  id: '/api/drill/compose',
  path: '/api/drill/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillAxesRoute = ApiDrillAxesRouteImport.update({
  id: '/api/drill/axes',
  path: '/api/drill/axes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartsAuthorRoute = ApiChartsAuthorRouteImport.update({
  id: '/api/charts/author',
  path: '/api/charts/author',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appReportsReportIdRoute = appReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => appRouteRoute,
} as any)
const appCockpitConversationIdRoute =
  appCockpitConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => appCockpitRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cockpit': typeof appCockpitRouteRouteWithChildren
  '/governance': typeof appGovernanceRoute
  '/library': typeof appLibraryRoute
  '/metadata': typeof appMetadataRoute
  '/operating-model': typeof appOperatingModelRoute
  '/settings': typeof appSettingsRoute
  '/workflows': typeof appWorkflowsRoute
  '/api/awaiting-input': typeof ApiAwaitingInputRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/health': typeof ApiHealthRoute
  '/api/probe-sql': typeof ApiProbeSqlRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/running-runs': typeof ApiRunningRunsRoute
  '/api/shipped-metric-dag': typeof ApiShippedMetricDagRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflow-progress': typeof ApiWorkflowProgressRoute
  '/cockpit/$conversationId': typeof appCockpitConversationIdRoute
  '/reports/$reportId': typeof appReportsReportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/charts/author': typeof ApiChartsAuthorRoute
  '/api/drill/axes': typeof ApiDrillAxesRoute
  '/api/drill/compose': typeof ApiDrillComposeRoute
  '/api/drill/node': typeof ApiDrillNodeRoute
  '/api/reports/mint': typeof ApiReportsMintRoute
  '/cockpit/': typeof appCockpitIndexRoute
  '/reports/': typeof appReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/governance': typeof appGovernanceRoute
  '/library': typeof appLibraryRoute
  '/metadata': typeof appMetadataRoute
  '/operating-model': typeof appOperatingModelRoute
  '/settings': typeof appSettingsRoute
  '/workflows': typeof appWorkflowsRoute
  '/api/awaiting-input': typeof ApiAwaitingInputRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/health': typeof ApiHealthRoute
  '/api/probe-sql': typeof ApiProbeSqlRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/running-runs': typeof ApiRunningRunsRoute
  '/api/shipped-metric-dag': typeof ApiShippedMetricDagRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflow-progress': typeof ApiWorkflowProgressRoute
  '/cockpit/$conversationId': typeof appCockpitConversationIdRoute
  '/reports/$reportId': typeof appReportsReportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/charts/author': typeof ApiChartsAuthorRoute
  '/api/drill/axes': typeof ApiDrillAxesRoute
  '/api/drill/compose': typeof ApiDrillComposeRoute
  '/api/drill/node': typeof ApiDrillNodeRoute
  '/api/reports/mint': typeof ApiReportsMintRoute
  '/cockpit': typeof appCockpitIndexRoute
  '/reports': typeof appReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/cockpit': typeof appCockpitRouteRouteWithChildren
  '/(app)/governance': typeof appGovernanceRoute
  '/(app)/library': typeof appLibraryRoute
  '/(app)/metadata': typeof appMetadataRoute
  '/(app)/operating-model': typeof appOperatingModelRoute
  '/(app)/settings': typeof appSettingsRoute
  '/(app)/workflows': typeof appWorkflowsRoute
  '/api/awaiting-input': typeof ApiAwaitingInputRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/health': typeof ApiHealthRoute
  '/api/probe-sql': typeof ApiProbeSqlRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/running-runs': typeof ApiRunningRunsRoute
  '/api/shipped-metric-dag': typeof ApiShippedMetricDagRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflow-progress': typeof ApiWorkflowProgressRoute
  '/(app)/cockpit/$conversationId': typeof appCockpitConversationIdRoute
  '/(app)/reports/$reportId': typeof appReportsReportIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/charts/author': typeof ApiChartsAuthorRoute
  '/api/drill/axes': typeof ApiDrillAxesRoute
  '/api/drill/compose': typeof ApiDrillComposeRoute
  '/api/drill/node': typeof ApiDrillNodeRoute
  '/api/reports/mint': typeof ApiReportsMintRoute
  '/(app)/cockpit/': typeof appCockpitIndexRoute
  '/(app)/reports/': typeof appReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cockpit'
    | '/governance'
    | '/library'
    | '/metadata'
    | '/operating-model'
    | '/settings'
    | '/workflows'
    | '/api/awaiting-input'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/health'
    | '/api/probe-sql'
    | '/api/run-sql'
    | '/api/running-runs'
    | '/api/shipped-metric-dag'
    | '/api/upload'
    | '/api/workflow-progress'
    | '/cockpit/$conversationId'
    | '/reports/$reportId'
    | '/api/auth/$'
    | '/api/charts/author'
    | '/api/drill/axes'
    | '/api/drill/compose'
    | '/api/drill/node'
    | '/api/reports/mint'
    | '/cockpit/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/governance'
    | '/library'
    | '/metadata'
    | '/operating-model'
    | '/settings'
    | '/workflows'
    | '/api/awaiting-input'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/health'
    | '/api/probe-sql'
    | '/api/run-sql'
    | '/api/running-runs'
    | '/api/shipped-metric-dag'
    | '/api/upload'
    | '/api/workflow-progress'
    | '/cockpit/$conversationId'
    | '/reports/$reportId'
    | '/api/auth/$'
    | '/api/charts/author'
    | '/api/drill/axes'
    | '/api/drill/compose'
    | '/api/drill/node'
    | '/api/reports/mint'
    | '/cockpit'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/cockpit'
    | '/(app)/governance'
    | '/(app)/library'
    | '/(app)/metadata'
    | '/(app)/operating-model'
    | '/(app)/settings'
    | '/(app)/workflows'
    | '/api/awaiting-input'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/health'
    | '/api/probe-sql'
    | '/api/run-sql'
    | '/api/running-runs'
    | '/api/shipped-metric-dag'
    | '/api/upload'
    | '/api/workflow-progress'
    | '/(app)/cockpit/$conversationId'
    | '/(app)/reports/$reportId'
    | '/api/auth/$'
    | '/api/charts/author'
    | '/api/drill/axes'
    | '/api/drill/compose'
    | '/api/drill/node'
    | '/api/reports/mint'
    | '/(app)/cockpit/'
    | '/(app)/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  ApiAwaitingInputRoute: typeof ApiAwaitingInputRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiProbeSqlRoute: typeof ApiProbeSqlRoute
  ApiRunSqlRoute: typeof ApiRunSqlRoute
  ApiRunningRunsRoute: typeof ApiRunningRunsRoute
  ApiShippedMetricDagRoute: typeof ApiShippedMetricDagRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWorkflowProgressRoute: typeof ApiWorkflowProgressRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChartsAuthorRoute: typeof ApiChartsAuthorRoute
  ApiDrillAxesRoute: typeof ApiDrillAxesRoute
  ApiDrillComposeRoute: typeof ApiDrillComposeRoute
  ApiDrillNodeRoute: typeof ApiDrillNodeRoute
  ApiReportsMintRoute: typeof ApiReportsMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow-progress': {
      id: '/api/workflow-progress'
      path: '/api/workflow-progress'
      fullPath: '/api/workflow-progress'
      preLoaderRoute: typeof ApiWorkflowProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipped-metric-dag': {
      id: '/api/shipped-metric-dag'
      path: '/api/shipped-metric-dag'
      fullPath: '/api/shipped-metric-dag'
      preLoaderRoute: typeof ApiShippedMetricDagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/running-runs': {
      id: '/api/running-runs'
      path: '/api/running-runs'
      fullPath: '/api/running-runs'
      preLoaderRoute: typeof ApiRunningRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-sql': {
      id: '/api/run-sql'
      path: '/api/run-sql'
      fullPath: '/api/run-sql'
      preLoaderRoute: typeof ApiRunSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probe-sql': {
      id: '/api/probe-sql'
      path: '/api/probe-sql'
      fullPath: '/api/probe-sql'
      preLoaderRoute: typeof ApiProbeSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awaiting-input': {
      id: '/api/awaiting-input'
      path: '/api/awaiting-input'
      fullPath: '/api/awaiting-input'
      preLoaderRoute: typeof ApiAwaitingInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/workflows': {
      id: '/(app)/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof appWorkflowsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/operating-model': {
      id: '/(app)/operating-model'
      path: '/operating-model'
      fullPath: '/operating-model'
      preLoaderRoute: typeof appOperatingModelRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/metadata': {
      id: '/(app)/metadata'
      path: '/metadata'
      fullPath: '/metadata'
      preLoaderRoute: typeof appMetadataRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/library': {
      id: '/(app)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/governance': {
      id: '/(app)/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof appGovernanceRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cockpit': {
      id: '/(app)/cockpit'
      path: '/cockpit'
      fullPath: '/cockpit'
      preLoaderRoute: typeof appCockpitRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/reports/': {
      id: '/(app)/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof appReportsIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cockpit/': {
      id: '/(app)/cockpit/'
      path: '/'
      fullPath: '/cockpit/'
      preLoaderRoute: typeof appCockpitIndexRouteImport
      parentRoute: typeof appCockpitRouteRoute
    }
    '/api/reports/mint': {
      id: '/api/reports/mint'
      path: '/api/reports/mint'
      fullPath: '/api/reports/mint'
      preLoaderRoute: typeof ApiReportsMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drill/node': {
      id: '/api/drill/node'
      path: '/api/drill/node'
      fullPath: '/api/drill/node'
      preLoaderRoute: typeof ApiDrillNodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drill/compose': {
      id: '/api/drill/compose'
      path: '/api/drill/compose'
      fullPath: '/api/drill/compose'
      preLoaderRoute: typeof ApiDrillComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drill/axes': {
      id: '/api/drill/axes'
      path: '/api/drill/axes'
      fullPath: '/api/drill/axes'
      preLoaderRoute: typeof ApiDrillAxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts/author': {
      id: '/api/charts/author'
      path: '/api/charts/author'
      fullPath: '/api/charts/author'
      preLoaderRoute: typeof ApiChartsAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/reports/$reportId': {
      id: '/(app)/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof appReportsReportIdRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/cockpit/$conversationId': {
      id: '/(app)/cockpit/$conversationId'
      path: '/$conversationId'
      fullPath: '/cockpit/$conversationId'
      preLoaderRoute: typeof appCockpitConversationIdRouteImport
      parentRoute: typeof appCockpitRouteRoute
    }
  }
}

interface appCockpitRouteRouteChildren {
  appCockpitConversationIdRoute: typeof appCockpitConversationIdRoute
  appCockpitIndexRoute: typeof appCockpitIndexRoute
}

const appCockpitRouteRouteChildren: appCockpitRouteRouteChildren = {
  appCockpitConversationIdRoute: appCockpitConversationIdRoute,
  appCockpitIndexRoute: appCockpitIndexRoute,
}

const appCockpitRouteRouteWithChildren = appCockpitRouteRoute._addFileChildren(
  appCockpitRouteRouteChildren,
)

interface appRouteRouteChildren {
  appCockpitRouteRoute: typeof appCockpitRouteRouteWithChildren
  appGovernanceRoute: typeof appGovernanceRoute
  appLibraryRoute: typeof appLibraryRoute
  appMetadataRoute: typeof appMetadataRoute
  appOperatingModelRoute: typeof appOperatingModelRoute
  appSettingsRoute: typeof appSettingsRoute
  appWorkflowsRoute: typeof appWorkflowsRoute
  appReportsReportIdRoute: typeof appReportsReportIdRoute
  appReportsIndexRoute: typeof appReportsIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appCockpitRouteRoute: appCockpitRouteRouteWithChildren,
  appGovernanceRoute: appGovernanceRoute,
  appLibraryRoute: appLibraryRoute,
  appMetadataRoute: appMetadataRoute,
  appOperatingModelRoute: appOperatingModelRoute,
  appSettingsRoute: appSettingsRoute,
  appWorkflowsRoute: appWorkflowsRoute,
  appReportsReportIdRoute: appReportsReportIdRoute,
  appReportsIndexRoute: appReportsIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  ApiAwaitingInputRoute: ApiAwaitingInputRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiProbeSqlRoute: ApiProbeSqlRoute,
  ApiRunSqlRoute: ApiRunSqlRoute,
  ApiRunningRunsRoute: ApiRunningRunsRoute,
  ApiShippedMetricDagRoute: ApiShippedMetricDagRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWorkflowProgressRoute: ApiWorkflowProgressRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChartsAuthorRoute: ApiChartsAuthorRoute,
  ApiDrillAxesRoute: ApiDrillAxesRoute,
  ApiDrillComposeRoute: ApiDrillComposeRoute,
  ApiDrillNodeRoute: ApiDrillNodeRoute,
  ApiReportsMintRoute: ApiReportsMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
