/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkflowProgressRouteImport } from './routes/api/workflow-progress'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiShippedMetricDagRouteImport } from './routes/api/shipped-metric-dag'
import { Route as ApiRunningRunsRouteImport } from './routes/api/running-runs'
import { Route as ApiRunSqlRouteImport } from './routes/api/run-sql'
import { Route as ApiProbeSqlRouteImport } from './routes/api/probe-sql'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiAwaitingInputRouteImport } from './routes/api/awaiting-input'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as ApiReportsMintRouteImport } from './routes/api/reports/mint'
import { Route as ApiDrillComposeRouteImport } from './routes/api/drill/compose'
import { Route as ApiDrillAxesRouteImport } from './routes/api/drill/axes'
import { Route as ApiChartsAuthorRouteImport } from './routes/api/charts/author'
import { Route as appWorkspaceWsIdRouteRouteImport } from './routes/(app)/workspace/$wsId/route'
import { Route as appWorkspaceWsIdWorkflowsRouteImport } from './routes/(app)/workspace/$wsId/workflows'
import { Route as appWorkspaceWsIdOperatingModelRouteImport } from './routes/(app)/workspace/$wsId/operating-model'
import { Route as appWorkspaceWsIdMetadataRouteImport } from './routes/(app)/workspace/$wsId/metadata'
import { Route as appWorkspaceWsIdLibraryRouteImport } from './routes/(app)/workspace/$wsId/library'
import { Route as appWorkspaceWsIdGovernanceRouteImport } from './routes/(app)/workspace/$wsId/governance'
import { Route as appWorkspaceWsIdCockpitRouteRouteImport } from './routes/(app)/workspace/$wsId/cockpit/route'
import { Route as appWorkspaceWsIdReportsIndexRouteImport } from './routes/(app)/workspace/$wsId/reports/index'
import { Route as appWorkspaceWsIdCockpitIndexRouteImport } from './routes/(app)/workspace/$wsId/cockpit/index'
import { Route as appWorkspaceWsIdReportsReportIdRouteImport } from './routes/(app)/workspace/$wsId/reports/$reportId'
import { Route as appWorkspaceWsIdCockpitConversationIdRouteImport } from './routes/(app)/workspace/$wsId/cockpit/$conversationId'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkflowProgressRoute = ApiWorkflowProgressRouteImport.update({
  id: '/api/workflow-progress',
  path: '/api/workflow-progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShippedMetricDagRoute = ApiShippedMetricDagRouteImport.update({
  id: '/api/shipped-metric-dag',
  path: '/api/shipped-metric-dag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunningRunsRoute = ApiRunningRunsRouteImport.update({
  id: '/api/running-runs',
  path: '/api/running-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRunSqlRoute = ApiRunSqlRouteImport.update({
  id: '/api/run-sql',
  path: '/api/run-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProbeSqlRoute = ApiProbeSqlRouteImport.update({
  id: '/api/probe-sql',
  path: '/api/probe-sql',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAwaitingInputRoute = ApiAwaitingInputRouteImport.update({
  id: '/api/awaiting-input',
  path: '/api/awaiting-input',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const ApiReportsMintRoute = ApiReportsMintRouteImport.update({
  id: '/api/reports/mint',
  path: '/api/reports/mint',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillComposeRoute = ApiDrillComposeRouteImport.update({
  id: '/api/drill/compose',
  path: '/api/drill/compose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDrillAxesRoute = ApiDrillAxesRouteImport.update({
  id: '/api/drill/axes',
  path: '/api/drill/axes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChartsAuthorRoute = ApiChartsAuthorRouteImport.update({
  id: '/api/charts/author',
  path: '/api/charts/author',
  getParentRoute: () => rootRouteImport,
} as any)
const appWorkspaceWsIdRouteRoute = appWorkspaceWsIdRouteRouteImport.update({
  id: '/workspace/$wsId',
  path: '/workspace/$wsId',
  getParentRoute: () => appRouteRoute,
} as any)
const appWorkspaceWsIdWorkflowsRoute =
  appWorkspaceWsIdWorkflowsRouteImport.update({
    id: '/workflows',
    path: '/workflows',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdOperatingModelRoute =
  appWorkspaceWsIdOperatingModelRouteImport.update({
    id: '/operating-model',
    path: '/operating-model',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdMetadataRoute =
  appWorkspaceWsIdMetadataRouteImport.update({
    id: '/metadata',
    path: '/metadata',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdLibraryRoute = appWorkspaceWsIdLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => appWorkspaceWsIdRouteRoute,
} as any)
const appWorkspaceWsIdGovernanceRoute =
  appWorkspaceWsIdGovernanceRouteImport.update({
    id: '/governance',
    path: '/governance',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdCockpitRouteRoute =
  appWorkspaceWsIdCockpitRouteRouteImport.update({
    id: '/cockpit',
    path: '/cockpit',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdReportsIndexRoute =
  appWorkspaceWsIdReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdCockpitIndexRoute =
  appWorkspaceWsIdCockpitIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => appWorkspaceWsIdCockpitRouteRoute,
  } as any)
const appWorkspaceWsIdReportsReportIdRoute =
  appWorkspaceWsIdReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => appWorkspaceWsIdRouteRoute,
  } as any)
const appWorkspaceWsIdCockpitConversationIdRoute =
  appWorkspaceWsIdCockpitConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => appWorkspaceWsIdCockpitRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof appSettingsRoute
  '/api/awaiting-input': typeof ApiAwaitingInputRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/probe-sql': typeof ApiProbeSqlRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/running-runs': typeof ApiRunningRunsRoute
  '/api/shipped-metric-dag': typeof ApiShippedMetricDagRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflow-progress': typeof ApiWorkflowProgressRoute
  '/workspace/$wsId': typeof appWorkspaceWsIdRouteRouteWithChildren
  '/api/charts/author': typeof ApiChartsAuthorRoute
  '/api/drill/axes': typeof ApiDrillAxesRoute
  '/api/drill/compose': typeof ApiDrillComposeRoute
  '/api/reports/mint': typeof ApiReportsMintRoute
  '/workspace/$wsId/cockpit': typeof appWorkspaceWsIdCockpitRouteRouteWithChildren
  '/workspace/$wsId/governance': typeof appWorkspaceWsIdGovernanceRoute
  '/workspace/$wsId/library': typeof appWorkspaceWsIdLibraryRoute
  '/workspace/$wsId/metadata': typeof appWorkspaceWsIdMetadataRoute
  '/workspace/$wsId/operating-model': typeof appWorkspaceWsIdOperatingModelRoute
  '/workspace/$wsId/workflows': typeof appWorkspaceWsIdWorkflowsRoute
  '/workspace/$wsId/cockpit/$conversationId': typeof appWorkspaceWsIdCockpitConversationIdRoute
  '/workspace/$wsId/reports/$reportId': typeof appWorkspaceWsIdReportsReportIdRoute
  '/workspace/$wsId/cockpit/': typeof appWorkspaceWsIdCockpitIndexRoute
  '/workspace/$wsId/reports/': typeof appWorkspaceWsIdReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof appSettingsRoute
  '/api/awaiting-input': typeof ApiAwaitingInputRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/probe-sql': typeof ApiProbeSqlRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/running-runs': typeof ApiRunningRunsRoute
  '/api/shipped-metric-dag': typeof ApiShippedMetricDagRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflow-progress': typeof ApiWorkflowProgressRoute
  '/workspace/$wsId': typeof appWorkspaceWsIdRouteRouteWithChildren
  '/api/charts/author': typeof ApiChartsAuthorRoute
  '/api/drill/axes': typeof ApiDrillAxesRoute
  '/api/drill/compose': typeof ApiDrillComposeRoute
  '/api/reports/mint': typeof ApiReportsMintRoute
  '/workspace/$wsId/governance': typeof appWorkspaceWsIdGovernanceRoute
  '/workspace/$wsId/library': typeof appWorkspaceWsIdLibraryRoute
  '/workspace/$wsId/metadata': typeof appWorkspaceWsIdMetadataRoute
  '/workspace/$wsId/operating-model': typeof appWorkspaceWsIdOperatingModelRoute
  '/workspace/$wsId/workflows': typeof appWorkspaceWsIdWorkflowsRoute
  '/workspace/$wsId/cockpit/$conversationId': typeof appWorkspaceWsIdCockpitConversationIdRoute
  '/workspace/$wsId/reports/$reportId': typeof appWorkspaceWsIdReportsReportIdRoute
  '/workspace/$wsId/cockpit': typeof appWorkspaceWsIdCockpitIndexRoute
  '/workspace/$wsId/reports': typeof appWorkspaceWsIdReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/api/awaiting-input': typeof ApiAwaitingInputRoute
  '/api/chat': typeof ApiChatRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/api/probe-sql': typeof ApiProbeSqlRoute
  '/api/run-sql': typeof ApiRunSqlRoute
  '/api/running-runs': typeof ApiRunningRunsRoute
  '/api/shipped-metric-dag': typeof ApiShippedMetricDagRoute
  '/api/upload': typeof ApiUploadRoute
  '/api/workflow-progress': typeof ApiWorkflowProgressRoute
  '/(app)/workspace/$wsId': typeof appWorkspaceWsIdRouteRouteWithChildren
  '/api/charts/author': typeof ApiChartsAuthorRoute
  '/api/drill/axes': typeof ApiDrillAxesRoute
  '/api/drill/compose': typeof ApiDrillComposeRoute
  '/api/reports/mint': typeof ApiReportsMintRoute
  '/(app)/workspace/$wsId/cockpit': typeof appWorkspaceWsIdCockpitRouteRouteWithChildren
  '/(app)/workspace/$wsId/governance': typeof appWorkspaceWsIdGovernanceRoute
  '/(app)/workspace/$wsId/library': typeof appWorkspaceWsIdLibraryRoute
  '/(app)/workspace/$wsId/metadata': typeof appWorkspaceWsIdMetadataRoute
  '/(app)/workspace/$wsId/operating-model': typeof appWorkspaceWsIdOperatingModelRoute
  '/(app)/workspace/$wsId/workflows': typeof appWorkspaceWsIdWorkflowsRoute
  '/(app)/workspace/$wsId/cockpit/$conversationId': typeof appWorkspaceWsIdCockpitConversationIdRoute
  '/(app)/workspace/$wsId/reports/$reportId': typeof appWorkspaceWsIdReportsReportIdRoute
  '/(app)/workspace/$wsId/cockpit/': typeof appWorkspaceWsIdCockpitIndexRoute
  '/(app)/workspace/$wsId/reports/': typeof appWorkspaceWsIdReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/api/awaiting-input'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/probe-sql'
    | '/api/run-sql'
    | '/api/running-runs'
    | '/api/shipped-metric-dag'
    | '/api/upload'
    | '/api/workflow-progress'
    | '/workspace/$wsId'
    | '/api/charts/author'
    | '/api/drill/axes'
    | '/api/drill/compose'
    | '/api/reports/mint'
    | '/workspace/$wsId/cockpit'
    | '/workspace/$wsId/governance'
    | '/workspace/$wsId/library'
    | '/workspace/$wsId/metadata'
    | '/workspace/$wsId/operating-model'
    | '/workspace/$wsId/workflows'
    | '/workspace/$wsId/cockpit/$conversationId'
    | '/workspace/$wsId/reports/$reportId'
    | '/workspace/$wsId/cockpit/'
    | '/workspace/$wsId/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/api/awaiting-input'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/probe-sql'
    | '/api/run-sql'
    | '/api/running-runs'
    | '/api/shipped-metric-dag'
    | '/api/upload'
    | '/api/workflow-progress'
    | '/workspace/$wsId'
    | '/api/charts/author'
    | '/api/drill/axes'
    | '/api/drill/compose'
    | '/api/reports/mint'
    | '/workspace/$wsId/governance'
    | '/workspace/$wsId/library'
    | '/workspace/$wsId/metadata'
    | '/workspace/$wsId/operating-model'
    | '/workspace/$wsId/workflows'
    | '/workspace/$wsId/cockpit/$conversationId'
    | '/workspace/$wsId/reports/$reportId'
    | '/workspace/$wsId/cockpit'
    | '/workspace/$wsId/reports'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/settings'
    | '/api/awaiting-input'
    | '/api/chat'
    | '/api/chat-stream'
    | '/api/probe-sql'
    | '/api/run-sql'
    | '/api/running-runs'
    | '/api/shipped-metric-dag'
    | '/api/upload'
    | '/api/workflow-progress'
    | '/(app)/workspace/$wsId'
    | '/api/charts/author'
    | '/api/drill/axes'
    | '/api/drill/compose'
    | '/api/reports/mint'
    | '/(app)/workspace/$wsId/cockpit'
    | '/(app)/workspace/$wsId/governance'
    | '/(app)/workspace/$wsId/library'
    | '/(app)/workspace/$wsId/metadata'
    | '/(app)/workspace/$wsId/operating-model'
    | '/(app)/workspace/$wsId/workflows'
    | '/(app)/workspace/$wsId/cockpit/$conversationId'
    | '/(app)/workspace/$wsId/reports/$reportId'
    | '/(app)/workspace/$wsId/cockpit/'
    | '/(app)/workspace/$wsId/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  ApiAwaitingInputRoute: typeof ApiAwaitingInputRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
  ApiProbeSqlRoute: typeof ApiProbeSqlRoute
  ApiRunSqlRoute: typeof ApiRunSqlRoute
  ApiRunningRunsRoute: typeof ApiRunningRunsRoute
  ApiShippedMetricDagRoute: typeof ApiShippedMetricDagRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiWorkflowProgressRoute: typeof ApiWorkflowProgressRoute
  ApiChartsAuthorRoute: typeof ApiChartsAuthorRoute
  ApiDrillAxesRoute: typeof ApiDrillAxesRoute
  ApiDrillComposeRoute: typeof ApiDrillComposeRoute
  ApiReportsMintRoute: typeof ApiReportsMintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workflow-progress': {
      id: '/api/workflow-progress'
      path: '/api/workflow-progress'
      fullPath: '/api/workflow-progress'
      preLoaderRoute: typeof ApiWorkflowProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shipped-metric-dag': {
      id: '/api/shipped-metric-dag'
      path: '/api/shipped-metric-dag'
      fullPath: '/api/shipped-metric-dag'
      preLoaderRoute: typeof ApiShippedMetricDagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/running-runs': {
      id: '/api/running-runs'
      path: '/api/running-runs'
      fullPath: '/api/running-runs'
      preLoaderRoute: typeof ApiRunningRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/run-sql': {
      id: '/api/run-sql'
      path: '/api/run-sql'
      fullPath: '/api/run-sql'
      preLoaderRoute: typeof ApiRunSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/probe-sql': {
      id: '/api/probe-sql'
      path: '/api/probe-sql'
      fullPath: '/api/probe-sql'
      preLoaderRoute: typeof ApiProbeSqlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/awaiting-input': {
      id: '/api/awaiting-input'
      path: '/api/awaiting-input'
      fullPath: '/api/awaiting-input'
      preLoaderRoute: typeof ApiAwaitingInputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/api/reports/mint': {
      id: '/api/reports/mint'
      path: '/api/reports/mint'
      fullPath: '/api/reports/mint'
      preLoaderRoute: typeof ApiReportsMintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drill/compose': {
      id: '/api/drill/compose'
      path: '/api/drill/compose'
      fullPath: '/api/drill/compose'
      preLoaderRoute: typeof ApiDrillComposeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drill/axes': {
      id: '/api/drill/axes'
      path: '/api/drill/axes'
      fullPath: '/api/drill/axes'
      preLoaderRoute: typeof ApiDrillAxesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/charts/author': {
      id: '/api/charts/author'
      path: '/api/charts/author'
      fullPath: '/api/charts/author'
      preLoaderRoute: typeof ApiChartsAuthorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/workspace/$wsId': {
      id: '/(app)/workspace/$wsId'
      path: '/workspace/$wsId'
      fullPath: '/workspace/$wsId'
      preLoaderRoute: typeof appWorkspaceWsIdRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/workspace/$wsId/workflows': {
      id: '/(app)/workspace/$wsId/workflows'
      path: '/workflows'
      fullPath: '/workspace/$wsId/workflows'
      preLoaderRoute: typeof appWorkspaceWsIdWorkflowsRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/operating-model': {
      id: '/(app)/workspace/$wsId/operating-model'
      path: '/operating-model'
      fullPath: '/workspace/$wsId/operating-model'
      preLoaderRoute: typeof appWorkspaceWsIdOperatingModelRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/metadata': {
      id: '/(app)/workspace/$wsId/metadata'
      path: '/metadata'
      fullPath: '/workspace/$wsId/metadata'
      preLoaderRoute: typeof appWorkspaceWsIdMetadataRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/library': {
      id: '/(app)/workspace/$wsId/library'
      path: '/library'
      fullPath: '/workspace/$wsId/library'
      preLoaderRoute: typeof appWorkspaceWsIdLibraryRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/governance': {
      id: '/(app)/workspace/$wsId/governance'
      path: '/governance'
      fullPath: '/workspace/$wsId/governance'
      preLoaderRoute: typeof appWorkspaceWsIdGovernanceRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/cockpit': {
      id: '/(app)/workspace/$wsId/cockpit'
      path: '/cockpit'
      fullPath: '/workspace/$wsId/cockpit'
      preLoaderRoute: typeof appWorkspaceWsIdCockpitRouteRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/reports/': {
      id: '/(app)/workspace/$wsId/reports/'
      path: '/reports'
      fullPath: '/workspace/$wsId/reports/'
      preLoaderRoute: typeof appWorkspaceWsIdReportsIndexRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/cockpit/': {
      id: '/(app)/workspace/$wsId/cockpit/'
      path: '/'
      fullPath: '/workspace/$wsId/cockpit/'
      preLoaderRoute: typeof appWorkspaceWsIdCockpitIndexRouteImport
      parentRoute: typeof appWorkspaceWsIdCockpitRouteRoute
    }
    '/(app)/workspace/$wsId/reports/$reportId': {
      id: '/(app)/workspace/$wsId/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/workspace/$wsId/reports/$reportId'
      preLoaderRoute: typeof appWorkspaceWsIdReportsReportIdRouteImport
      parentRoute: typeof appWorkspaceWsIdRouteRoute
    }
    '/(app)/workspace/$wsId/cockpit/$conversationId': {
      id: '/(app)/workspace/$wsId/cockpit/$conversationId'
      path: '/$conversationId'
      fullPath: '/workspace/$wsId/cockpit/$conversationId'
      preLoaderRoute: typeof appWorkspaceWsIdCockpitConversationIdRouteImport
      parentRoute: typeof appWorkspaceWsIdCockpitRouteRoute
    }
  }
}

interface appWorkspaceWsIdCockpitRouteRouteChildren {
  appWorkspaceWsIdCockpitConversationIdRoute: typeof appWorkspaceWsIdCockpitConversationIdRoute
  appWorkspaceWsIdCockpitIndexRoute: typeof appWorkspaceWsIdCockpitIndexRoute
}

const appWorkspaceWsIdCockpitRouteRouteChildren: appWorkspaceWsIdCockpitRouteRouteChildren =
  {
    appWorkspaceWsIdCockpitConversationIdRoute:
      appWorkspaceWsIdCockpitConversationIdRoute,
    appWorkspaceWsIdCockpitIndexRoute: appWorkspaceWsIdCockpitIndexRoute,
  }

const appWorkspaceWsIdCockpitRouteRouteWithChildren =
  appWorkspaceWsIdCockpitRouteRoute._addFileChildren(
    appWorkspaceWsIdCockpitRouteRouteChildren,
  )

interface appWorkspaceWsIdRouteRouteChildren {
  appWorkspaceWsIdCockpitRouteRoute: typeof appWorkspaceWsIdCockpitRouteRouteWithChildren
  appWorkspaceWsIdGovernanceRoute: typeof appWorkspaceWsIdGovernanceRoute
  appWorkspaceWsIdLibraryRoute: typeof appWorkspaceWsIdLibraryRoute
  appWorkspaceWsIdMetadataRoute: typeof appWorkspaceWsIdMetadataRoute
  appWorkspaceWsIdOperatingModelRoute: typeof appWorkspaceWsIdOperatingModelRoute
  appWorkspaceWsIdWorkflowsRoute: typeof appWorkspaceWsIdWorkflowsRoute
  appWorkspaceWsIdReportsReportIdRoute: typeof appWorkspaceWsIdReportsReportIdRoute
  appWorkspaceWsIdReportsIndexRoute: typeof appWorkspaceWsIdReportsIndexRoute
}

const appWorkspaceWsIdRouteRouteChildren: appWorkspaceWsIdRouteRouteChildren = {
  appWorkspaceWsIdCockpitRouteRoute:
    appWorkspaceWsIdCockpitRouteRouteWithChildren,
  appWorkspaceWsIdGovernanceRoute: appWorkspaceWsIdGovernanceRoute,
  appWorkspaceWsIdLibraryRoute: appWorkspaceWsIdLibraryRoute,
  appWorkspaceWsIdMetadataRoute: appWorkspaceWsIdMetadataRoute,
  appWorkspaceWsIdOperatingModelRoute: appWorkspaceWsIdOperatingModelRoute,
  appWorkspaceWsIdWorkflowsRoute: appWorkspaceWsIdWorkflowsRoute,
  appWorkspaceWsIdReportsReportIdRoute: appWorkspaceWsIdReportsReportIdRoute,
  appWorkspaceWsIdReportsIndexRoute: appWorkspaceWsIdReportsIndexRoute,
}

const appWorkspaceWsIdRouteRouteWithChildren =
  appWorkspaceWsIdRouteRoute._addFileChildren(
    appWorkspaceWsIdRouteRouteChildren,
  )

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRoute
  appWorkspaceWsIdRouteRoute: typeof appWorkspaceWsIdRouteRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRoute,
  appWorkspaceWsIdRouteRoute: appWorkspaceWsIdRouteRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  ApiAwaitingInputRoute: ApiAwaitingInputRoute,
  ApiChatRoute: ApiChatRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
  ApiProbeSqlRoute: ApiProbeSqlRoute,
  ApiRunSqlRoute: ApiRunSqlRoute,
  ApiRunningRunsRoute: ApiRunningRunsRoute,
  ApiShippedMetricDagRoute: ApiShippedMetricDagRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiWorkflowProgressRoute: ApiWorkflowProgressRoute,
  ApiChartsAuthorRoute: ApiChartsAuthorRoute,
  ApiDrillAxesRoute: ApiDrillAxesRoute,
  ApiDrillComposeRoute: ApiDrillComposeRoute,
  ApiReportsMintRoute: ApiReportsMintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
